# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.8 on 2026-09-04 23:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields
import wagtail.contrib.routable_page.models

import springfield.blog.fields
import springfield.cms.fields
import springfield.cms.rich_text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0149_remove_blogarticlepage_custom_navigation_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "internal_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Editor-only label for organizing pages in the CMS. Not shown to the public; the public title is used when blank.",
                        max_length=255,
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("description", springfield.cms.rich_text.RichTextField(blank=True, help_text="A short description used on the index page.")),
                (
                    "updated_date",
                    models.DateField(blank=True, help_text="Shown as “Last updated on …”. Leave empty to show only the published date.", null=True),
                ),
                ("hide_dates", models.BooleanField(default=False, help_text="Hide the published and updated dates on this article.")),
                (
                    "hero_style",
                    models.CharField(
                        choices=[
                            ("standard_image", "Standard image"),
                            ("large_image", "Large featured image"),
                            ("text_only", "No image, text only"),
                            ("video", "Featured video"),
                        ],
                        default="standard_image",
                        help_text="Layout for the article header.",
                        max_length=32,
                    ),
                ),
                (
                    "hero_video",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Video shown in the header when the hero style is “Featured video”.", null=True
                    ),
                ),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "bottom_banner",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Optional banner to be displayed at the bottom of the article content."
                    ),
                ),
                (
                    "related_articles",
                    springfield.cms.fields.StreamField(
                        blank=True,
                        block_lookup={},
                        help_text=(
                            "Up to 4 related articles shown at the bottom. "
                            "Remaining empty slots are filled with articles that match by topic and tag, then topic, then tag, up to 4."
                        ),
                    ),
                ),
                ("hide_related", models.BooleanField(default=False, help_text="Hide the Related Articles section on this article.")),
                (
                    "custom_navigation",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Override the page header navigation with this menu. "
                            "If unset, the page inherits its nearest ancestor's custom navigation, "
                            "then the site default navigation, then the built-in navigation."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.navigationsnippet",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional image for article cards and lists. Falls back to the featured image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Article Page",
                "verbose_name_plural": "Blog Article Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("bio", springfield.cms.rich_text.RichTextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Author",
                "verbose_name_plural": "Blog Authors",
                "abstract": False,
                "unique_together": {("slug", "locale"), ("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="BlogArticleAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="article_authors", to="blog.blogarticlepage"
                    ),
                ),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="blog.blogauthor")),
            ],
            options={
                "verbose_name": "Blog Article Author",
                "verbose_name_plural": "Blog Article Authors",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "internal_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Editor-only label for organizing pages in the CMS. Not shown to the public; the public title is used when blank.",
                        max_length=255,
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("page_heading", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "featured_articles",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Up to 4 featured articles shown at the top of the index page.", null=True
                    ),
                ),
                (
                    "featured_topics",
                    springfield.cms.fields.StreamField(
                        blank=True,
                        block_lookup={},
                        help_text="Up to 8 topics shown at the top of the index page. If empty, the topics with the most articles are shown.",
                        null=True,
                    ),
                ),
                (
                    "feed_exclusions",
                    springfield.cms.fields.StreamField(
                        blank=True,
                        block_lookup={},
                        help_text=(
                            "Articles with these topics or tags are left out of the full article list and the latest-articles section, "
                            "and these tags are hidden on article cards. Topic pages and ?tag= links are unaffected."
                        ),
                        null=True,
                    ),
                ),
                ("article_sections", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "custom_navigation",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Override the page header navigation with this menu. "
                            "If unset, the page inherits its nearest ancestor's custom navigation, "
                            "then the site default navigation, then the built-in navigation."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.navigationsnippet",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
                "verbose_name_plural": "Blog Index Pages",
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Tag",
                "verbose_name_plural": "Blog Tags",
                "abstract": False,
                "unique_together": {("name", "locale"), ("slug", "locale"), ("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="BlogTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("name", models.CharField()),
                ("slug", models.SlugField()),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Topic",
                "verbose_name_plural": "Blog Topics",
                "abstract": False,
                "unique_together": {("slug", "locale"), ("translation_key", "locale")},
            },
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="topic",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="blog_articles", to="blog.blogtopic"),
        ),
        migrations.CreateModel(
            name="BlogTopicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "internal_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Editor-only label for organizing pages in the CMS. Not shown to the public; the public title is used when blank.",
                        max_length=255,
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("page_heading", springfield.cms.fields.StreamField(blank=True, block_lookup={})),
                (
                    "featured_articles",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Up to 4 featured articles shown at the top. These are left out of the list below."
                    ),
                ),
                (
                    "custom_navigation",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Override the page header navigation with this menu. "
                            "If unset, the page inherits its nearest ancestor's custom navigation, "
                            "then the site default navigation, then the built-in navigation."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.navigationsnippet",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="topic_pages", to="blog.blogtopic")),
            ],
            options={
                "verbose_name": "Blog Topic Page",
                "verbose_name_plural": "Blog Topic Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TaggedBlogArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tagged_items", to="blog.blogarticlepage"
                    ),
                ),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tagged_articles", to="blog.blogtag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="tags",
            field=springfield.blog.fields.LocalizedClusterTaggableManager(
                blank=True, help_text="A comma-separated list of tags.", through="blog.TaggedBlogArticle", to="blog.BlogTag", verbose_name="Tags"
            ),
        ),
    ]
