# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.17 on 2026-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_move_content_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogtopicpage",
            name="hide_breadcrumb",
            field=models.BooleanField(default=False, help_text='Hide the "Blog Home" back link on this topic page.'),
        ),
        migrations.AddField(
            model_name="blogtopicpage",
            name="hide_topics",
            field=models.BooleanField(default=False, help_text="Hide the topic bubbles on this topic page."),
        ),
    ]
