# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_move_content_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticlepage",
            name="image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="listing_image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
    ]
