# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.18 on 2025-03-13 13:21

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0004_rename_bedrockrendition_springfieldrendition"),
        ("wagtailcore", "0093_uploadedfile"),
        ("firefox", "0002_delete_firefoxosfeedlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturesCallToActionSnippet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("heading", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=500)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                ("locale", models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale")),
            ],
            options={
                "verbose_name": "Features Call To Action Snippet",
                "verbose_name_plural": "Features Call To Action Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="FeaturesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("sub_title", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FeaturesDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("desc", models.CharField(blank=True, help_text="A short description used on index page.", max_length=500)),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "article_media",
                    wagtail.fields.StreamField(
                        [
                            (
                                "video",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("image", wagtail.images.blocks.ImageChooserBlock(help_text="Video placeholder image.")),
                                        ("title", wagtail.blocks.CharBlock(char_max_length=100, help_text="Video embed accessible title.")),
                                        (
                                            "youtube_video_id",
                                            wagtail.blocks.CharBlock(
                                                char_max_length=100, help_text="YouTube video string ID to pass to embed.", required=False
                                            ),
                                        ),
                                        (
                                            "cdn_video_url",
                                            wagtail.blocks.URLBlock(
                                                char_max_length=255,
                                                help_text="URL for webm format video hosted on https://assets.mozilla.net/.",
                                                required=False,
                                            ),
                                        ),
                                    ],
                                    max_num=1,
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                ("featured_article", models.BooleanField(default=False, help_text="Check to set as a featured article on the index page.")),
                (
                    "call_to_action_bottom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="firefox.featurescalltoactionsnippet",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.springfieldimage"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
