# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.18 on 2025-03-14 15:08

from django.db import migrations

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("firefox", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuresdetailpage",
            name="article_media",
            field=wagtail.fields.StreamField(
                [
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock(help_text="Video placeholder image.")),
                                ("title", wagtail.blocks.CharBlock(char_max_length=100, help_text="Video embed accessible title.")),
                                (
                                    "youtube_video_id",
                                    wagtail.blocks.CharBlock(
                                        char_max_length=100, help_text="YouTube video string ID to pass to embed.", required=False
                                    ),
                                ),
                                (
                                    "cdn_video_url",
                                    wagtail.blocks.URLBlock(
                                        char_max_length=255,
                                        help_text="URL for webm format video hosted on https://assets.mozilla.net/ - loading from elsewhere will cause security (CSP) issues and the video may be blocked",  # noqa E501
                                        required=False,
                                    ),
                                ),
                            ],
                            max_num=1,
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
