# Generated by Django 4.2.20 on 2025-03-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("firefox", "0004_alter_featuresdetailpage_article_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featurescalltoactionsnippet",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
    ]
