# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-06 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firefox", "0005_alter_featurescalltoactionsnippet_locale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuresindexpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FeaturesDetailPage",
        ),
        migrations.DeleteModel(
            name="FeaturesIndexPage",
        ),
    ]
