# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-06 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firefox", "0006_remove_featuresindexpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeaturesCallToActionSnippet",
        ),
    ]
