# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("firefox", "0006_remove_featuresdetailpage_call_to_action_bottom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirefoxReferralData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_id", models.CharField(max_length=10, unique=True)),
                ("install_count", models.PositiveIntegerField(default=0)),
                ("last_refreshed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
