# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firefox", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firefoxreferraldata",
            name="last_refreshed_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
