# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firefox", "0008_alter_firefoxreferraldata_last_refreshed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firefoxreferraldata",
            name="referral_id",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
