# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 4.2.20 on 2025-03-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0004_rename_bedrockrendition_springfieldrendition"),
    ]

    operations = [
        migrations.AddField(
            model_name="springfieldimage",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="description"),
        ),
    ]
