# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# ruff: noqa: E501
# Generated by Django 5.2.5 on 2025-09-08 03:36

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_springfieldimage_description"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsNewPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("hero", 14),
                            ("features", 23),
                            ("highlights", 27),
                            ("subscribe_banner", 28),
                            ("tag_cards", 35),
                            ("qr_code_banner", 37),
                        ],
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h1", "H1"), ("h2", "H2"), ("h3", "H3"), ("h4", "H4"), ("h5", "H5"), ("h6", "H6")],
                                    "inline_form": True,
                                },
                            ),
                            3: ("wagtail.blocks.ChoiceBlock", [], {"choices": [("center", "Center"), ("left", "Left")], "inline_form": True}),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_size", 2), ("alignment", 3), ("eyebrow_text", 4), ("headline_text", 4), ("subheadline_text", 4)]],
                                {"classname": "compact-form"},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("outline", "Outline"), ("secondary", "Secondary")], "inline_form": True, "required": False},
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "inline_form": True, "label": "External link", "required": False},
                            ),
                            8: ("wagtail.blocks.BooleanBlock", (), {"default": False, "inline_form": True, "required": False}),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("android", "Android"),
                                        ("apple", "Apple"),
                                        ("arrow-right", "Arrow Right"),
                                        ("design", "Design"),
                                        ("language", "Language"),
                                        ("shield", "Shield"),
                                    ],
                                    "inline_form": True,
                                    "required": False,
                                },
                            ),
                            10: ("wagtail.blocks.CharBlock", (), {}),
                            11: ("wagtail.blocks.CharBlock", (), {"label": "Button Text"}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("theme", 6), ("external", 7), ("center", 8), ("icon", 9), ("link", 10), ("label", 11)]],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {"max_num": 1, "min_num": 0}),
                            14: ("wagtail.blocks.StructBlock", [[("image", 1), ("heading", 5), ("button", 13)]], {}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_size", 2), ("alignment", 3), ("eyebrow_text", 4), ("headline_text", 4), ("subheadline_text", 4)]],
                                {},
                            ),
                            16: ("wagtail.blocks.CharBlock", (), {"label": "Link Text"}),
                            17: ("wagtail.blocks.BooleanBlock", (), {"default": False, "label": "External link", "required": False}),
                            18: ("wagtail.blocks.StructBlock", [[("link", 10), ("label", 16), ("external", 17)]], {}),
                            19: ("wagtail.blocks.ListBlock", (18,), {"label": "Call to Action", "max_num": 1, "min_num": 0}),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"]},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("eyebrow", 4), ("headline", 20), ("content", 20), ("button", 13)]],
                                {},
                            ),
                            22: ("wagtail.blocks.ListBlock", (21,), {}),
                            23: ("wagtail.blocks.StructBlock", [[("heading", 15), ("cta", 19), ("rows", 22)]], {}),
                            24: ("wagtail.images.blocks.ImageChooserBlock", (), {"help_text": "Optional dark mode image", "required": False}),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("dark_image", 24), ("headline", 20), ("content", 20), ("button", 13)]],
                                {},
                            ),
                            26: ("wagtail.blocks.ListBlock", (25,), {}),
                            27: ("wagtail.blocks.StructBlock", [[("heading", 15), ("cards", 26)]], {}),
                            28: ("wagtail.blocks.StructBlock", [[("heading", 15)]], {}),
                            29: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("android", "Android"),
                                        ("apple", "Apple"),
                                        ("arrow-right", "Arrow Right"),
                                        ("design", "Design"),
                                        ("language", "Language"),
                                        ("shield", "Shield"),
                                    ]
                                },
                            ),
                            30: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("purple", "Purple"), ("blue", "Blue"), ("orange", "Orange"), ("yellow", "Yellow")], "required": False},
                            ),
                            31: ("wagtail.blocks.StructBlock", [[("title", 10), ("icon", 29), ("color", 30)]], {}),
                            32: ("wagtail.blocks.ListBlock", (31,), {"max_num": 3, "min_num": 1}),
                            33: ("wagtail.blocks.StructBlock", [[("headline", 20), ("content", 20), ("button", 13), ("tags", 32)]], {}),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: ("wagtail.blocks.StructBlock", [[("heading", 15), ("cards", 34)]], {}),
                            36: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Content to encode in the QR code, e.g., a URL or text.", "required": True},
                            ),
                            37: ("wagtail.blocks.StructBlock", [[("qr_content", 36), ("headline", 20), ("content", 20)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
