# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.2 on 2025-08-13 20:07

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_springfieldimage_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsNewPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("heading", 3), ("paragraph", 4), ("image", 5)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "superscript", "subscript", "strikethrough"], "required": False},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("text-center", "Center"), ("text-left", "Left")], "inline_form": True},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h1", "H1"), ("h2", "H2"), ("h3", "H3"), ("h4", "H4"), ("h5", "H5"), ("h6", "H6")],
                                    "inline_form": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("accent_text", 0), ("headline_text", 0), ("subheadline_text", 0), ("alignment", 1), ("heading_size", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.RichTextBlock", (), {}),
                            5: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
