# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.6 on 2025-10-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_freeformpage_whatsnewindexpage_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTranslationData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("percent_translated", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "source_page",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translation_data", to="wagtailcore.page"),
                ),
                (
                    "translated_page",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_translation_data", to="wagtailcore.page"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["source_page"], name="cms_pagetra_source__cca145_idx")],
                "unique_together": {("source_page", "translated_page")},
            },
        ),
    ]
