# Generated by Django 5.2.7 on 2025-10-07 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_pagetranslationdata"),
        ("cms", "0009_alter_freeformpage_content_and_more"),
    ]

    operations = []
