# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.6 on 2025-10-13 15:08

from copy import deepcopy

from django.db import migrations

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import BaseBlockOperation


class ChangeBannerHeadingStructureOperation(BaseBlockOperation):
    def apply(self, block_value):
        value = deepcopy(block_value)
        return self._transform_banner(value)

    def _transform_banner(self, banner):
        """Move headline text and content fields into the heading block."""
        new_banner = {**banner}
        new_banner["heading"] = {
            "superheading_text": "",
            "heading_text": banner.get("headline"),
            "subheading_text": banner.get("content"),
        }
        return new_banner

    @property
    def operation_name_fragment(self):
        return "change_banner_heading_structure"


operations = [
    (ChangeBannerHeadingStructureOperation(), "banner"),
]


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_merge_20251008_0924"),
    ]

    operations = [
        MigrateStreamData(app_name="cms", model_name="FreeFormPage", field_name="content", operations_and_block_paths=operations),
        MigrateStreamData(app_name="cms", model_name="WhatsNewPage", field_name="content", operations_and_block_paths=operations),
    ]
