# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-15 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_alter_freeformpage_content_and_more"),
        ("cms", "0011_auto_20251013_0808"),
    ]

    operations = []
