# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-23 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0019_alter_freeformpage_content_and_more"),
        ("cms", "0019_merge_20251023_0657"),
    ]

    operations = []
