# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-10-27 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0017_merge_20251021_0534"),
        ("cms", "0020_merge_20251023_0826"),
    ]

    operations = []
