# Generated by Django 5.2.7 on 2025-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0021_auto_20251105_1127"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpringfieldLocale",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wagtailcore.locale",),
        ),
    ]
