# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-13 18:48

import json

from django.db import migrations


def update_banner_types(data):
    for i, block in enumerate(data):
        if block.get("type") == "banner":
            value = {**block.get("value", {})}
            settings = value.get("settings", {})
            if settings.get("theme", "").startswith("filled"):
                block["type"] = "kit_banner"
                data[i] = block
    return data


def update_banner_blocks(apps, schema_editor):
    FreeFormPage = apps.get_model("cms", "FreeFormPage")
    WhatsNewPage = apps.get_model("cms", "WhatsNewPage")
    for page in WhatsNewPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = update_banner_types(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = update_banner_types(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = update_banner_types(page.content.raw_data)
        page.save(update_fields=["content"])

    for page in FreeFormPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = update_banner_types(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = update_banner_types(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = update_banner_types(page.content.raw_data)
        page.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_springfieldlocale"),
    ]

    operations = [
        migrations.RunPython(update_banner_blocks, migrations.RunPython.noop),
    ]
