# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-07 15:11

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_articleindexpage_articledetailpage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadFirefoxCallToActionSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("heading", wagtail.fields.RichTextField()),
                ("description", wagtail.fields.RichTextField()),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Firefox Call To Action Snippet",
                "verbose_name_plural": "Download Firefox Call To Action Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
