# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.7 on 2025-11-17 19:57

import json
from uuid import uuid4

from django.db import migrations


def update_banners(data):
    for i, block in enumerate(data):
        if block.get("type") == "banner":
            value = {**block.get("value", {})}
            image = value.get("image")
            qr_code = value.get("qr_code")
            video = value.get("video")

            if qr_code:
                value["media"] = [
                    {
                        "type": "qr_code",
                        "value": {
                            "data": qr_code,
                            "background": image,
                        },
                        "id": str(uuid4()),
                    }
                ]
            elif image:
                value["media"] = [
                    {
                        "type": "image",
                        "value": {
                            "image": image,
                            "dark_image": None,
                        },
                        "id": str(uuid4()),
                    }
                ]
                block["value"] = value
                data[i] = block
            elif video:
                value["media"] = [{**video[0], "type": "video"}]

            block["value"] = value
            data[i] = block
    return data


def update_pages(apps, schema_editor):
    FreeFormPage = apps.get_model("cms", "FreeFormPage")
    WhatsNewPage = apps.get_model("cms", "WhatsNewPage")
    for page in WhatsNewPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = update_banners(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = update_banners(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = update_banners(page.content.raw_data)
        page.save(update_fields=["content"])

    for page in FreeFormPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = update_banners(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = update_banners(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = update_banners(page.content.raw_data)
        page.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_auto_20251113_1048"),
    ]

    operations = [
        migrations.RunPython(update_pages, migrations.RunPython.noop),
    ]
