# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-26 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_auto_20251120_0451"),
        ("cms", "0024_merge_20251112_0617"),
    ]

    operations = []
