# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-24 21:04

import json

# Wagtail block values data can be of type wagtail.blocks.stream_block.StreamValue.RawDataView
# which are mutable sequences
from collections.abc import MutableSequence
from uuid import uuid4

from django.db import migrations


def update_blocks(data):
    value = {**data.get("value", {})}
    image = value.get("image")
    dark_image = value.get("dark_image")
    video = value.get("video")

    if image:
        value["media"] = [
            {
                "type": "image",
                "value": {
                    "image": image,
                    "dark_image": dark_image,
                },
                "id": str(uuid4()),
            }
        ]
    elif video:
        value["media"] = [{**video[0], "type": "video"}]

    data["value"] = value
    return data


def walk_and_transform(data):
    """Recursively walk through the block tree and transform buttons wherever found."""
    if isinstance(data, dict):
        # Transform the icon card button field if it exists and is a list
        if data.get("type") in ["intro", "media_content"]:
            data = update_blocks(data)

        # Recursively transform nested structures
        for key, value in data.items():
            if isinstance(value, (dict, list, MutableSequence)):
                data[key] = walk_and_transform(value)

    elif isinstance(data, (list, MutableSequence)):
        for i, item in enumerate(data):
            if isinstance(item, (dict, list, MutableSequence)):
                data[i] = walk_and_transform(item)

    return data


def update_pages(apps, schema_editor):
    FreeFormPage = apps.get_model("cms", "FreeFormPage")
    WhatsNewPage = apps.get_model("cms", "WhatsNewPage")
    for page in WhatsNewPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = walk_and_transform(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = walk_and_transform(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = walk_and_transform(page.content.raw_data)
        page.save(update_fields=["content"])

    for page in FreeFormPage.objects.all():
        published_revision = page.live_revision
        latest_revision = page.latest_revision
        if published_revision:
            content = json.loads(published_revision.content["content"])
            updated_value = walk_and_transform(content)
            published_revision.content["content"] = json.dumps(updated_value)
            published_revision.save(update_fields=["content"])
        if latest_revision and latest_revision != published_revision:
            content = json.loads(latest_revision.content["content"])
            updated_value = walk_and_transform(content)
            latest_revision.content["content"] = json.dumps(updated_value)
            latest_revision.save(update_fields=["content"])
        page.content.raw_data = walk_and_transform(page.content.raw_data)
        page.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0025_merge_0023_auto_20251120_0451_0024_auto_20251117_1157"),
    ]

    operations = [
        migrations.RunPython(update_pages, migrations.RunPython.noop),
    ]
