# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-11-26 21:29

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0025_merge_0023_auto_20251120_0451_0024_auto_20251117_1157"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("upper_content", springfield.cms.fields.StreamField(block_lookup={})),
                ("lower_content", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
