# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-12-02 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0024_auto_20251120_1353"),
        ("cms", "0026_auto_20251124_1304"),
    ]

    operations = []
