# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-12-10 18:35

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_merge_0024_auto_20251120_1353_0026_auto_20251124_1304"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("sub_title", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticleDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("featured", models.BooleanField(default=False, help_text="Check to set as a featured article on the index page.")),
                ("description", wagtail.fields.RichTextField(blank=True, help_text="A short description used on index page.")),
                ("content", wagtail.fields.RichTextField(blank=True)),
                ("call_to_action", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.springfieldimage"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DownloadFirefoxCallToActionSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("heading", wagtail.fields.RichTextField()),
                ("description", wagtail.fields.RichTextField()),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Firefox Call To Action Snippet",
                "verbose_name_plural": "Download Firefox Call To Action Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
