# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2025-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_merge_0024_auto_20251120_1353_0026_auto_20251124_1304"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetranslationdata",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
