# Generated by Django 5.2.9 on 2025-12-15 19:12

from django.db import migrations

from springfield.cms.utils import create_page_translation_data


def populate_enabled_field(apps, schema_editor):
    """Populate PageTranslationData.enabled by calling create_page_translation_data"""
    from wagtail.models import Page  # import directly to allow calling .get_translations()

    PageTranslationData = apps.get_model("cms", "PageTranslationData")

    # Get all unique source page IDs
    source_page_ids = PageTranslationData.objects.values_list("source_page_id", flat=True).distinct()

    updated_count = 0
    for source_page_id in source_page_ids:
        try:
            # Get the actual Page instance (not historical model)
            source_page = Page.objects.get(id=source_page_id)
            # Call the function that populates PageTranslationData with enabled field
            create_page_translation_data(source_page)
            updated_count += 1
        except Exception as e:
            # If we can't process the page, skip it
            print(f"Error processing page {source_page_id}: {e}")
            continue

    print(f"Updated PageTranslationData for {updated_count} source pages")


def reverse_populate_enabled_field(apps, schema_editor):
    """Reset all enabled fields to True"""
    PageTranslationData = apps.get_model("cms", "PageTranslationData")
    PageTranslationData.objects.all().update(enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0028_pagetranslationdata_enabled"),
    ]

    operations = [
        migrations.RunPython(populate_enabled_field, reverse_populate_enabled_field),
    ]
