# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.8 on 2025-12-04 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0028_merge_20251204_0801"),
        ("cms", "0028_merge_20251204_0851"),
    ]

    operations = []
