# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-06 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0028_articleindexpage_articledetailpage_and_more"),
        ("cms", "0029_prefooterctasnippet"),
    ]

    operations = []
