# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2025-12-12 20:25

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.models.preview


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0030_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreFooterCTASnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("label", models.CharField(default="Get Firefox", max_length=255)),
                ("link", models.URLField(blank=True, max_length=255)),
                ("analytics_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre Footer Call to Action",
                "verbose_name_plural": "Pre Footer Call to Action",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
