# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-06 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0030_downloadpage_prefooterctaformsnippet"),
        ("cms", "0030_merge_20260106_1435"),
    ]

    operations = []
