# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-08 20:13

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0031_merge_20260106_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadpage",
            name="content",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="download_page_featured_images",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="platform",
            field=models.CharField(
                choices=[
                    ("windows", "Windows"),
                    ("mac", "macOS"),
                    ("linux", "Linux"),
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("chromebook", "Chromebook"),
                ],
                default="windows",
                help_text="The platform this download page is for (e.g., Windows, macOS, Linux).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="subheading",
            field=wagtail.fields.RichTextField(default="Subheading"),
        ),
    ]
