# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-22 12:11

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields
import springfield.cms.models.pages
import springfield.cms.models.snippets


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0032_migrate_existing_image_variants"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThanksPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
            ],
            options={
                "abstract": False,
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="DownloadPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("mac", "macOS"),
                            ("linux", "Linux"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("chromebook", "Chromebook"),
                        ],
                        default="windows",
                        help_text="The platform this download page is for (e.g., Windows, macOS, Linux).",
                        max_length=50,
                    ),
                ),
                ("subheading", wagtail.fields.RichTextField(default="Subheading")),
                ("intro_footer_text", wagtail.fields.RichTextField(blank=True, null=True)),
                ("content", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="download_page_featured_images",
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Page",
                "verbose_name_plural": "Download Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BannerSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("kit_theme", models.BooleanField(default=False, help_text="Use the Kit theme for this banner.")),
                ("heading", wagtail.fields.RichTextField()),
                ("content", wagtail.fields.RichTextField()),
                ("buttons", springfield.cms.fields.StreamField(blank=True, block_lookup={})),
                ("qr_code", models.CharField(blank=True)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Snippet",
                "verbose_name_plural": "Banner Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PreFooterCTAFormSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("heading", wagtail.fields.RichTextField()),
                ("subheading", wagtail.fields.RichTextField()),
                ("analytics_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre Footer Call To Action Form",
                "verbose_name_plural": "Pre Footer Call To Action Forms",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
    ]
