# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-09 14:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields
import springfield.cms.models.snippets


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0032_downloadpage_content_downloadpage_featured_image_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeBannerSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("heading", wagtail.fields.RichTextField()),
                ("content", wagtail.fields.RichTextField()),
                ("buttons", springfield.cms.fields.StreamField(blank=True, block_lookup={})),
                ("qr_code", models.CharField()),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Banner Snippet",
                "verbose_name_plural": "QR Code Banner Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
    ]
