# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-22 18:29

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0033_thankspage_downloadpage_bannersnippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadpage",
            name="pre_footer",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="pre_footer",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
