# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import json

import django
from django.contrib.contenttypes.models import ContentType
from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models

import wagtail.fields

import springfield


def page_to_streamfield(page):
    changed = False
    try:
        json.loads(page.content)
    except ValueError:
        page.content = json.dumps(
            [{"type": "text", "value": page.content}],
        )
        changed = True
    else:
        # It's already valid JSON. Leave it.
        pass

    return page, changed


def pagerevision_to_streamfield(revision_data):
    changed = False
    content = revision_data.get("content")
    if content:
        try:
            json.loads(content)
        except ValueError:
            revision_data["content"] = json.dumps([{"value": content, "type": "text"}], cls=DjangoJSONEncoder)
            changed = True
        else:
            # It's already valid JSON. Leave it.
            pass
    return revision_data, changed


def page_to_richtext(page):
    changed = False
    if page.content:
        try:
            content_data = json.loads(page.content)
        except ValueError:
            # It's not apparently a StreamField. Leave it.
            pass
        else:
            page.content = "".join([child["value"] for child in content_data if child["type"] == "text"])
            changed = True

    return page, changed


def pagerevision_to_richtext(revision_data):
    changed = False
    content = revision_data.get("content", "definitely non-JSON string")
    if content:
        try:
            content_data = json.loads(content)
        except ValueError:
            # It's not apparently a StreamField. Leave it.
            pass
        else:
            raw_text = "".join([child["value"] for child in content_data if child["type"] == "text"])
            revision_data["content"] = raw_text
            changed = True
    return revision_data, changed


def convert(apps, schema_editor, page_converter, pagerevision_converter):
    ArticleDetailPage = apps.get_model("cms", "ArticleDetailPage")
    content_type = ContentType.objects.get_for_model(ArticleDetailPage)
    Revision = apps.get_model("wagtailcore", "Revision")

    for page in ArticleDetailPage.objects.all():
        page, changed = page_converter(page)
        if changed:
            page.save()

        for revision in Revision.objects.filter(content_type_id=content_type.pk, object_id=page.pk):
            revision_data = revision.content
            revision_data, changed = pagerevision_converter(revision_data)
            if changed:
                revision.content = revision_data
                revision.save()


def convert_to_streamfield(apps, schema_editor):
    return convert(apps, schema_editor, page_to_streamfield, pagerevision_to_streamfield)


def convert_to_richtext(apps, schema_editor):
    return convert(apps, schema_editor, page_to_richtext, pagerevision_to_richtext)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0034_downloadpage_pre_footer_thankspage_pre_footer"),
    ]

    operations = [
        # Data migration to convert existing ArticleDetailPage.content from RichText to StreamField
        # https://docs.wagtail.org/en/stable/advanced_topics/streamfield_migrations.html
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
        # Regular operations generated by Django makemigrations
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                help_text="A portrait-oriented image used in featured article cards.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                help_text="An icon used for listing articles on the index page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="other_articles_heading",
            field=wagtail.fields.RichTextField(default="Headline"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="other_articles_subheading",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="content",
            field=springfield.cms.fields.StreamField(block_lookup={}),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, help_text="A short description used on the index page."),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cms.springfieldimage",
                null=True,
                blank=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_tag",
            field=models.CharField(blank=True, help_text="A short tag to display above the article title on featured article cards."),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="link_text",
            field=models.CharField(default="Read more", help_text="Custom text for the 'Read more' link on article cards."),
        ),
    ]
