# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-15 20:12

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0034_thankspage"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadpage",
            name="intro_footer_text",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
