# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-28 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_articledetailpage_featured_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articledetailpage",
            name="call_to_action",
        ),
    ]
