# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0036_remove_articledetailpage_call_to_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="index_page_heading",
            field=models.CharField(blank=True, help_text="Custom heading to be used on the index page card."),
        ),
    ]
