# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-01-29 17:46

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields
import springfield.cms.models.pages


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0037_remove_articledetailpage_featured_tag_tag_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleThemePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", wagtail.fields.RichTextField()),
                ("subheading", wagtail.fields.RichTextField(blank=True)),
                ("featured_articles", springfield.cms.fields.StreamField(block_lookup={})),
                ("other_articles_heading", wagtail.fields.RichTextField()),
                ("other_articles_subheading", wagtail.fields.RichTextField(blank=True)),
                ("other_articles", springfield.cms.fields.StreamField(block_lookup={})),
            ],
            options={
                "abstract": False,
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
    ]
