# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-05 14:59

import uuid

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields
import springfield.cms.models.pages


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0037_remove_thankspage_pre_footer"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleThemePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", springfield.cms.fields.StreamField(block_lookup={}, default=[])),
            ],
            options={
                "abstract": False,
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
        migrations.RemoveField(
            model_name="articledetailpage",
            name="featured_tag",
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                help_text="A sticker image used in article cards.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField()),
                ("slug", models.SlugField()),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="tag",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles", to="cms.tag"),
        ),
    ]
