# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-04 18:06

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0038_articlethemepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlethemepage",
            name="featured_articles",
        ),
        migrations.RemoveField(
            model_name="articlethemepage",
            name="heading",
        ),
        migrations.RemoveField(
            model_name="articlethemepage",
            name="other_articles",
        ),
        migrations.RemoveField(
            model_name="articlethemepage",
            name="other_articles_heading",
        ),
        migrations.RemoveField(
            model_name="articlethemepage",
            name="other_articles_subheading",
        ),
        migrations.RemoveField(
            model_name="articlethemepage",
            name="subheading",
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="content",
            field=springfield.cms.fields.StreamField(block_lookup={}, default=[]),
        ),
    ]
