# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0039_remove_articlethemepage_featured_articles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                help_text="A sticker image used in article cards.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
    ]
