# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-11 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0041_merge_0038_0040"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadpage",
            name="pre_footer",
        ),
    ]
