# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-02-11 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0043_downloadindexpage"),
        ("cms", "0045_alter_articledetailpage_icon"),
    ]

    operations = []
