# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-12 15:35

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0046_merge_20260211_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlethemepage",
            name="upper_content",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
