# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.9 on 2026-02-12 19:15

import django.db.models.deletion
import springfield.cms.fields
import springfield.cms.models.pages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0047_articlethemepage_upper_content"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeFormPage2026",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_content",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Optional upper content. If present, the page will use a split layout.", null=True
                    ),
                ),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
            ],
            options={
                "verbose_name": "Free Form 2026 Page",
                "verbose_name_plural": "Free Form 2026 Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
    ]
