# Generated by Django 5.2.11 on 2026-02-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0047_articlethemepage_upper_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_image_dark_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_image_dark_mode_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode mobile variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_image_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional mobile variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="image_dark_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode variant of the article image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="image_dark_mode_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode mobile variant of the article image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="image_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional mobile variant of the article image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="sticker_dark_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode variant of the sticker.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="sticker_dark_mode_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode mobile variant of the sticker.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="sticker_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional mobile variant of the sticker.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="featured_image_dark_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="featured_image_dark_mode_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode mobile variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="featured_image_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional mobile variant of the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
    ]
