# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-02-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0048_add_image_variants_to_page_fks"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadindexpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="simplerichtextpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="structuralpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewindexpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cms.springfieldimage",
            ),
        ),
    ]
