# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-02-26 22:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0049_articledetailpage_og_image_articleindexpage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prefooterctasnippet",
            name="link",
        ),
        migrations.AlterField(
            model_name="prefooterctasnippet",
            name="analytics_id",
            field=models.CharField(default=uuid.uuid4),
        ),
    ]
