# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-02-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0050_remove_prefooterctasnippet_link_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannersnippet",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="expired",
            field=models.BooleanField(default=False, editable=False, verbose_name="expired"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="go live date/time"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="live",
            field=models.BooleanField(default=True, editable=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="bannersnippet",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="expired",
            field=models.BooleanField(default=False, editable=False, verbose_name="expired"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="go live date/time"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="live",
            field=models.BooleanField(default=True, editable=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="expired",
            field=models.BooleanField(default=False, editable=False, verbose_name="expired"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="go live date/time"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="live",
            field=models.BooleanField(default=True, editable=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="prefooterctaformsnippet",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="expired",
            field=models.BooleanField(default=False, editable=False, verbose_name="expired"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="go live date/time"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="live",
            field=models.BooleanField(default=True, editable=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time"),
        ),
        migrations.AddField(
            model_name="tag",
            name="expired",
            field=models.BooleanField(default=False, editable=False, verbose_name="expired"),
        ),
        migrations.AddField(
            model_name="tag",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
        ),
        migrations.AddField(
            model_name="tag",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="go live date/time"),
        ),
        migrations.AddField(
            model_name="tag",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="last published at"),
        ),
        migrations.AddField(
            model_name="tag",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="live",
            field=models.BooleanField(default=True, editable=False, verbose_name="live"),
        ),
        migrations.AddField(
            model_name="tag",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
    ]
