# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-03-04 20:59

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0052_convert_show_to_conditional_display"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeFormPage2026",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "upper_content",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Optional upper content. If present, the page will use a split layout.", null=True
                    ),
                ),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Free Form 2026 Page",
                "verbose_name_plural": "Free Form 2026 Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
