# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0053_freeformpage2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="show_pre_footer",
            field=models.BooleanField(default=True, help_text="If true, the page will display the default pre-footer section."),
        ),
    ]
