# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0054_freeformpage2026_show_pre_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="show_nav_cta",
            field=models.BooleanField(default=True, help_text="If true, the download button will appear in the navigation bar for this page."),
        ),
    ]
