# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-12 15:30

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields
import springfield.cms.models.pages


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0055_freeformpage2026_show_nav_cta"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True, help_text="A short description used on the index page.")),
                ("featured", models.BooleanField(default=False, help_text="Check to set as a featured article on the index page.")),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "featured_image",
                    models.ForeignKey(
                        help_text="A portrait-oriented image used in featured article cards.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "featured_image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the featured image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "featured_image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the featured image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "featured_image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the featured image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="blog_articles_tags", to="cms.tag")),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="blog_articles", to="cms.tag")),
            ],
            options={
                "verbose_name": "Blog Article Page",
                "verbose_name_plural": "Blog Article Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
                "verbose_name_plural": "Blog Index Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
    ]
