# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-17 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0056_alter_tag_unique_together_blogarticlepage_and_more"),
        ("cms", "0056_whatsnewpage2026"),
    ]

    operations = []
