# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0056_create_alias_locale_records"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prefooterctasnippet",
            old_name="label",
            new_name="label_old",
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="custom_label",
            field=models.CharField(
                blank=True, default="", help_text="Only used when 'Custom text' is selected above. Will be sent for translation.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="prefooterctasnippet",
            name="pretranslated_label",
            field=models.CharField(
                choices=[
                    ("custom", "Custom text"),
                    ("navigation-get-firefox", "Get Firefox"),
                    ("download-button-download-firefox", "Download Firefox"),
                ],
                default="navigation-get-firefox",
                help_text="Choose a pre-translated label. If 'Custom text' is selected, fill in the custom label below.",
                max_length=255,
            ),
        ),
    ]
