# Generated by Django 5.2.12 on 2026-03-18 00:43

import django.db.models.deletion
import springfield.cms.fields
import springfield.cms.models.pages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_whatsnewpage2026'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', springfield.cms.fields.StreamField(block_lookup={})),
                ('og_image', models.ForeignKey(blank=True, help_text='Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).', null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.springfieldimage')),
            ],
            options={
                'verbose_name': 'User Privacy Page',
                'verbose_name_plural': 'User Privacy Pages',
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, 'wagtailcore.page'),
        ),
    ]
