# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-18 20:54

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0057_freeformpage2026_show_qr_code_snippet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodesnippet",
            name="content",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="freeformpage2026",
            name="show_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, a floating QR code snippet will be displayed on the page."),
        ),
        migrations.AlterField(
            model_name="thankspage",
            name="show_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, a floating QR code snippet will be displayed on the page."),
        ),
        migrations.AlterField(
            model_name="whatsnewpage",
            name="show_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, a floating QR code snippet will be displayed on the page."),
        ),
        migrations.AlterField(
            model_name="whatsnewpage2026",
            name="show_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, a floating QR code snippet will be displayed on the page."),
        ),
    ]
