# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-01 14:52

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0058_qrcodesnippet_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freeformpage2026",
            name="content",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
