# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-03-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0058_qrcodesnippet_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrivacyPage",
            fields=[
                (
                    "freeformpage2026_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.freeformpage2026",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Privacy Page",
                "verbose_name_plural": "User Privacy Pages",
            },
            bases=("cms.freeformpage2026",),
        ),
    ]
