# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-08 18:53

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.fields
import springfield.cms.models.pages


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0060_create_alias_locale_records"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartWindowPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading_text", wagtail.fields.RichTextField()),
                ("subheading_text", wagtail.fields.RichTextField()),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                ("waitlist_button_label", models.CharField(default="Try Smart Window", max_length=255)),
                ("form_submit_label", models.CharField(default="Join the Waitlist", max_length=255)),
                ("thank_you_message", wagtail.fields.RichTextField(default='<p data-block-key="abcdef">Thank you!</p>')),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage")),
                (
                    "image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Window Page",
                "verbose_name_plural": "Smart Window Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
    ]
