# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-03 19:45

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0060_merge_20260403_1142"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="featured_image",
        ),
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="featured_image_dark_mode",
        ),
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="featured_image_dark_mode_mobile",
        ),
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="featured_image_mobile",
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="cards_lists",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="featured_articles",
            field=springfield.cms.fields.StreamField(
                blank=True, block_lookup={}, help_text="Up to 8 featured articles shown at the top of the index page.", null=True
            ),
        ),
    ]
