# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0060_create_alias_locale_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsnewpage",
            name="version",
            field=models.CharField(
                help_text="The version of Firefox this What's New page refers to, or 'general' for a non-version-specific page.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="whatsnewpage2026",
            name="version",
            field=models.CharField(
                help_text="The version of Firefox this What's New page refers to, or 'general' for a non-version-specific page.",
                max_length=10,
            ),
        ),
    ]
