# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0062_smartwindowpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="show_smart_window_button",
            field=models.CharField(
                choices=[("all", "Show to all users"), ("us_ca", "US and Canada only"), ("never", "Never show to any users")],
                default="us_ca",
                help_text="Controls whether the 'Try Smart Window' button is shown on the page. When not available, "
                "the Waitlist form is shown instead.",
            ),
        ),
    ]
