# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-13 23:07

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields
import springfield.cms.models.pages


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0063_smartwindowpage_show_smart_window_button_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartWindowExplainerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("upper_content", springfield.cms.fields.StreamField(block_lookup={})),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Window Explainer Page",
                "verbose_name_plural": "Smart Window Explainer Pages",
            },
            bases=(springfield.cms.models.pages.UTMParamsMixin, "wagtailcore.page"),
        ),
    ]
