# Generated by Django 5.2.12 on 2026-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0063_fix_compare_more_page_tree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articledetailpage",
            name="icon",
            field=models.CharField(blank=True, default="", help_text="Optional icon to display on icon article cards.", max_length=100),
        ),
    ]
