# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 23:53

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.blocks
import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0063_migrate_illustration_card_image_to_media"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartWindowExplainerPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("upper_content", springfield.cms.fields.StreamField(block_lookup={})),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Window Explainer Page",
                "verbose_name_plural": "Smart Window Explainer Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SmartWindowPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading_text", wagtail.fields.RichTextField()),
                ("subheading_text", wagtail.fields.RichTextField()),
                (
                    "animation",
                    models.URLField(
                        blank=True,
                        help_text="Link to a webm video from assets.mozilla.net.",
                        validators=[springfield.cms.blocks.validate_animation_url],
                    ),
                ),
                ("animation_alt", models.CharField(blank=True, help_text="Text for screen readers describing the video.", max_length=255)),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "show_smart_window_button",
                    models.CharField(
                        choices=[("all", "Show to all users"), ("us_ca", "US and Canada only"), ("never", "Never show to any users")],
                        default="us_ca",
                        help_text="Controls whether the 'Try Smart Window' button is shown on the page. When not available, "
                        "the Waitlist form is shown instead.",
                    ),
                ),
                ("nav_button_uid", models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Header Smart Window button.")),
                ("intro_button_uid", models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Intro Smart Window button.")),
                ("waitlist_submit_uid", models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Waitlist form submit button.")),
                ("waitlist_button_label", models.CharField(default="Try Smart Window", max_length=255)),
                ("form_submit_label", models.CharField(default="Join the Waitlist", max_length=255)),
                ("thank_you_message", wagtail.fields.RichTextField(default='<p data-block-key="abcdef">Thank you!</p>')),
                (
                    "privacy_notice",
                    wagtail.fields.RichTextField(
                        default='<p data-block-key="abcdef">I’m okay with Mozilla handling my info as explained in this '
                        '<a href="https://www.mozilla.org/privacy/websites/">Privacy Notice</a>.</p>'
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Used as fallback if an animation is provided.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "redirect_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page users will be taken to after clicking the Smart Window button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.smartwindowexplainerpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Window Page",
                "verbose_name_plural": "Smart Window Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
