# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 16:56

import uuid

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0064_smartwindowexplainerpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="intro_button_uid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Intro Smart Window button."),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="nav_button_uid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Header Smart Window button."),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="privacy_notice",
            field=wagtail.fields.RichTextField(
                default='<p data-block-key="abcdef">I’m okay with Mozilla handling my info as explained in this '
                '<a href="https://www.mozilla.org/privacy/websites/">Privacy Notice</a>.</p>'
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="waitlist_submit_uid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Waitlist form submit button."),
        ),
    ]
