# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0065_merge_20260415_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartwindowpage",
            name="show_smart_window_button",
            field=models.CharField(
                choices=[("all", "Show to all users"), ("allowed_territories", "US and Canada only"), ("never", "Never show to any users")],
                default="allowed_territories",
                help_text="Controls whether the 'Try Smart Window' button is shown on the page. When not available, "
                "the Waitlist form is shown instead.",
                max_length=20,
            ),
        ),
    ]
