# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 17:46

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0065_smartwindowpage_intro_button_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="animation",
            field=models.URLField(
                blank=True, help_text="Link to a webm video from assets.mozilla.net.", validators=[springfield.cms.blocks.validate_animation_url]
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="animation_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the video.", max_length=255),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="image",
            field=models.ForeignKey(
                help_text="Used as fallback if an animation is provided.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
    ]
