# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-16 18:36

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0066_alter_smartwindowpage_show_smart_window_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="copy_success_label",
            field=models.CharField(
                default="Copied", help_text="Label displayed when the link is successfully copied to the clipboard.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="copy_to_clipboard_label",
            field=models.CharField(
                default="Copy link to page", help_text="Label for the button that copies the page link to the clipboard.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="download_button_label",
            field=models.CharField(default="Download Firefox", help_text="Label for the button to download Firefox.", max_length=255),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="post_download_instructions",
            field=wagtail.fields.RichTextField(
                default="<p data-block-key='abcdef'>Return to this page after updating Firefox to unlock access to Smart Window BETA.</p>",
                help_text="Instructions displayed to the user for next steps after downloading Firefox.",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="update_button_label",
            field=models.CharField(
                default="How to update Firefox", help_text="Label for the button that appears if the user needs to update Firefox.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="update_instructions",
            field=wagtail.fields.RichTextField(
                default="<p data-block-key='abcdef'>Before you can try Smart Window, you’ll need to download the latest version of Firefox.</p>",
                help_text="Instructions displayed to the user if they need to update Firefox before trying Smart Window.",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="update_link",
            field=models.URLField(
                default="https://support.mozilla.org/en-US/products/firefox/installation-and-updates",
                help_text="URL for the update Firefox instructions page.",
            ),
        ),
    ]
