# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0061_alter_whatsnewpage_version_and_more"),
        ("cms", "0067_migrate_illustration_card_image_to_media"),
    ]

    operations = []
