# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-17 01:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0067_smartwindowpage_copy_success_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. "
                "The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download "
                "buttons. The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download "
                "buttons. The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download "
                "buttons. The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowexplainerpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download "
                "buttons. The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowexplainerpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowexplainerpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="intro_download_button_uid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Intro Download Firefox button."),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="nav_download_button_uid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Unique identifier for the Header Download Firefox button."),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="stub_attr_utm_campaign",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign` attribute on the page, used by download buttons. "
                "The value is only used if there's no `utm_campaign` in the URL query params.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="stub_attr_utm_campaign_force",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-force` attribute on the page, used by download "
                "buttons. The value overrides URL params AND clears any existing attribution cookie, forcing a fresh attribution request every time.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Force",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="stub_attr_utm_campaign_override",
            field=models.CharField(
                blank=True,
                help_text="If set, this value will be added as the `data-stub-attribution-campaign-override` attribute on the page, used by download "
                "buttons. The value overrides any `utm_campaign` in the URL, but respects an existing attribution cookie.",
                max_length=255,
                verbose_name="Stub Attribution UTM Campaign Override",
            ),
        ),
    ]
