# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0068_merge_20260415_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="redirect_page",
            field=models.ForeignKey(
                blank=True,
                help_text="The page users will be taken to after clicking the Smart Window button.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.smartwindowexplainerpage",
            ),
        ),
    ]
