# Generated by Django 5.2.12 on 2026-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_articledetailpage_stub_attr_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetailpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='articledetailpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='articleindexpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='articlethemepage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='articlethemepage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='downloadpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='downloadpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='freeformpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='freeformpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='freeformpage2026',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='freeformpage2026',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='smartwindowexplainerpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='smartwindowexplainerpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='smartwindowpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='smartwindowpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='stub_attr_utm_campaign_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('default', 'Default (used if no utm_campaign in URL)'), ('override', 'Override (replaces utm_campaign from URL, respects cookie)'), ('force', 'Force (replaces everything, clears attribution cookie)')], help_text='Controls how the campaign value is applied to download attribution.', max_length=20, verbose_name='Stub Attribution Mode'),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='stub_attr_utm_campaign_value',
            field=models.CharField(blank=True, help_text='The campaign value to use for stub attribution. Only used if a mode is selected above.', max_length=255, verbose_name='Stub Attribution Campaign Value'),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articledetailpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articleindexpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articlethemepage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articlethemepage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articlethemepage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='downloadpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage2026',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage2026',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='freeformpage2026',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowexplainerpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowexplainerpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowexplainerpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartwindowpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thankspage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thankspage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thankspage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage2026',
            name='stub_attr_utm_campaign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage2026',
            name='stub_attr_utm_campaign_force',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsnewpage2026',
            name='stub_attr_utm_campaign_override',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
