# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0069_merge_20260419_0930"),
    ]

    operations = [
        # NOTE: RemoveField operations for qr_code_floating_button have been
        # deferred to a follow-up PR to avoid dropping columns during deploy.
        migrations.AddField(
            model_name="freeformpage2026",
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, an updated floating QR code snippet will be displayed on the page."),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, an updated floating QR code snippet will be displayed on the page."),
        ),
        migrations.AddField(
            model_name="whatsnewpage",
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, an updated floating QR code snippet will be displayed on the page."),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, an updated floating QR code snippet will be displayed on the page."),
        ),
        migrations.AlterField(
            model_name="freeformpage2026",
            name="override_default_open",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qrcodefloatingsnippet",
            name="default_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="whatsnewpage",
            name="override_default_open",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="whatsnewpage2026",
            name="override_default_open",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
