# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-20 19:23

import uuid

from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0071_remove_legacy_stub_attr_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smartwindowpage",
            old_name="waitlist_button_label",
            new_name="smart_window_button_label",
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="thank_you_heading",
            field=wagtail.fields.RichTextField(default='<p data-block-key="abcdef">You’re on the list!</p>'),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="update_button_uid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier for the Update Firefox button that appears if the user needs to update."
            ),
        ),
    ]
