# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-20 22:49

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.models.snippets

OVERRIDE_IMAGE_HELP = "Override with an uploaded QR code image. Takes priority over the URL."
OVERRIDE_URL_HELP = "Override the snippet URL. A QR code will be generated from this. Not used if an override image is set."
SHOW_FLOATING_HELP = "If true, an updated floating QR code snippet will be displayed on the page."


def _add_page_fields(model_name):
    """Return the four AddField operations needed for each page type."""
    return [
        migrations.AddField(
            model_name=model_name,
            name="override_default_open",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name=model_name,
            name="override_image",
            field=models.ForeignKey(
                blank=True,
                help_text=OVERRIDE_IMAGE_HELP,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name=model_name,
            name="override_url",
            field=models.CharField(blank=True, help_text=OVERRIDE_URL_HELP),
        ),
        migrations.AddField(
            model_name=model_name,
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(default=False, help_text=SHOW_FLOATING_HELP),
        ),
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0071_remove_legacy_stub_attr_fields"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        *_add_page_fields("freeformpage2026"),
        *_add_page_fields("thankspage"),
        *_add_page_fields("whatsnewpage"),
        *_add_page_fields("whatsnewpage2026"),
        migrations.CreateModel(
            name="QRCodeFloatingSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                (
                    "has_unpublished_changes",
                    models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes"),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at"),
                ),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("heading", wagtail.fields.RichTextField(blank=True)),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="A QR code will be generated from this URL. Not used if an image is uploaded.",
                    ),
                ),
                ("default_open", models.BooleanField(default=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upload a QR code image. If set, this is used instead of generating one from the URL.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Floating Snippet",
                "verbose_name_plural": "QR Code Floating Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
    ]
