# Generated by Django 5.2.12 on 2026-04-20 22:36

import django.db.models.deletion
import springfield.cms.models.snippets
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0071_remove_legacy_stub_attr_fields'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeformpage2026',
            name='override_default_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeformpage2026',
            name='override_image',
            field=models.ForeignKey(blank=True, help_text='Override with an uploaded QR code image. Takes priority over the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.springfieldimage'),
        ),
        migrations.AddField(
            model_name='freeformpage2026',
            name='override_url',
            field=models.CharField(blank=True, help_text='Override the snippet URL. A QR code will be generated from this. Not used if an override image is set.'),
        ),
        migrations.AddField(
            model_name='freeformpage2026',
            name='show_floating_qr_code_snippet',
            field=models.BooleanField(default=False, help_text='If true, an updated floating QR code snippet will be displayed on the page.'),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='override_default_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='override_image',
            field=models.ForeignKey(blank=True, help_text='Override with an uploaded QR code image. Takes priority over the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.springfieldimage'),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='override_url',
            field=models.CharField(blank=True, help_text='Override the snippet URL. A QR code will be generated from this. Not used if an override image is set.'),
        ),
        migrations.AddField(
            model_name='thankspage',
            name='show_floating_qr_code_snippet',
            field=models.BooleanField(default=False, help_text='If true, an updated floating QR code snippet will be displayed on the page.'),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='override_default_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='override_image',
            field=models.ForeignKey(blank=True, help_text='Override with an uploaded QR code image. Takes priority over the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.springfieldimage'),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='override_url',
            field=models.CharField(blank=True, help_text='Override the snippet URL. A QR code will be generated from this. Not used if an override image is set.'),
        ),
        migrations.AddField(
            model_name='whatsnewpage',
            name='show_floating_qr_code_snippet',
            field=models.BooleanField(default=False, help_text='If true, an updated floating QR code snippet will be displayed on the page.'),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='override_default_open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='override_image',
            field=models.ForeignKey(blank=True, help_text='Override with an uploaded QR code image. Takes priority over the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.springfieldimage'),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='override_url',
            field=models.CharField(blank=True, help_text='Override the snippet URL. A QR code will be generated from this. Not used if an override image is set.'),
        ),
        migrations.AddField(
            model_name='whatsnewpage2026',
            name='show_floating_qr_code_snippet',
            field=models.BooleanField(default=False, help_text='If true, an updated floating QR code snippet will be displayed on the page.'),
        ),
        migrations.CreateModel(
            name='QRCodeFloatingSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('heading', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.RichTextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='A QR code will be generated from this URL. Not used if an image is uploaded.')),
                ('default_open', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, help_text='Upload a QR code image. If set, this is used instead of generating one from the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.springfieldimage')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'QR Code Floating Snippet',
                'verbose_name_plural': 'QR Code Floating Snippets',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
    ]
