# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-21 00:45

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0072_smartwindowpage_smart_window_button_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="mobile_message",
            field=wagtail.fields.RichTextField(
                default='<p data-block-key="abcdef">This experience is only available on desktop. '
                "Please open this page on your computer and update your browser to download</p>"
            ),
        ),
    ]
