# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0072_freeformpage2026_override_default_open_and_more"),
        ("cms", "0072_smartwindowpage_smart_window_button_label_and_more"),
    ]

    operations = []
