# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-20 17:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0072_rename_waitlist_button_label_smartwindowpage_smart_window_button_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartwindowpage",
            name="update_button_uid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier for the Update Firefox button that appears if the user needs to update."
            ),
        ),
    ]
