# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.13 on 2026-04-21 04:01

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0073_smartwindowpage_mobile_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartwindowpage",
            name="mobile_message",
            field=wagtail.fields.RichTextField(
                default='<p data-block-key="abcdef">This experience is only available on desktop. Please open this page on your computer.</p>'
            ),
        ),
    ]
