# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.13 on 2026-04-23 16:40

from django.db import migrations

import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0075_floating_qr_code_snippet_mixin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartwindowpage",
            name="post_download_instructions",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="<p data-block-key='abcdef'>Return to this page after updating Firefox to unlock access to Smart Window BETA.</p>",
                help_text="Instructions displayed to the user for next steps after downloading Firefox.",
            ),
        ),
    ]
