# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-02 15:05

import os
import sys

from django.db import migrations, models

from springfield.base.config_manager import config


def enable_siblings_for_feature_index_pages(apps, schema_editor):
    """
    Set show_sibling_detail_pages=True for feature ArticleIndexPages.

    Feature index pages have slug "all" and sit directly under a page with
    slug "features" — one per locale in the Wagtail tree. We identify them
    by slug rather than page type to avoid tying this migration to the
    ArticleThemePage content type.
    """
    # We don't need to update "features" pages in tests, in CI, or during the DB export.
    is_ci = os.environ.get("CI", "").lower() in ("1", "true", "yes")
    if "pytest" in sys.modules or is_ci or config("SQLITE_EXPORT_MODE", parser=bool, default="false"):
        return

    from wagtail.models import Page

    ArticleIndexPage = apps.get_model("cms", "ArticleIndexPage")

    # Collect paths of all "features" parent pages (one per locale).
    features_paths = set(Page.objects.filter(slug="features").values_list("path", flat=True))

    # In treebeard MP tree, the direct parent's path is path[:-steplen].
    # Wagtail uses steplen=4 for Page.
    steplen = Page.steplen

    to_update = [p.pk for p in ArticleIndexPage.objects.filter(slug="all") if p.path[:-steplen] in features_paths]

    if to_update:
        ArticleIndexPage.objects.filter(pk__in=to_update).update(show_sibling_detail_pages=True)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0076_alter_smartwindowpage_post_download_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleindexpage",
            name="show_sibling_detail_pages",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If checked, ArticleDetailPage siblings of this index page are included in the "
                    "article listing alongside its children. Enable for index pages whose detail "
                    "pages are siblings. Disable for index pages whose detail pages are children."
                ),
            ),
        ),
        migrations.RunPython(
            enable_siblings_for_feature_index_pages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
