# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-10 19:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0076_alter_smartwindowpage_post_download_instructions"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PretranslatedPhraseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PretranslatedPhrase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phrases",
                        to="cms.pretranslatedphrasecategory",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pretranslated Phrase",
                "verbose_name_plural": "Pretranslated Phrases",
                "abstract": False,
                "unique_together": {("category", "locale"), ("translation_key", "locale")},
            },
        ),
    ]
