# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-05-06 18:14

from django.db import migrations

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0076_alter_smartwindowpage_post_download_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articledetailpage",
            name="description",
            field=springfield.cms.rich_text.RichTextField(blank=True, help_text="A short description used on the index page."),
        ),
        migrations.AlterField(
            model_name="articleindexpage",
            name="other_articles_heading",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="articleindexpage",
            name="other_articles_subheading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bannersnippet",
            name="content",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="bannersnippet",
            name="heading",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="description",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="downloadfirefoxcalltoactionsnippet",
            name="heading",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="downloadpage",
            name="intro_footer_text",
            field=springfield.cms.rich_text.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="downloadpage",
            name="subheading",
            field=springfield.cms.rich_text.RichTextField(default="Subheading"),
        ),
        migrations.AlterField(
            model_name="prefooterctaformsnippet",
            name="heading",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="prefooterctaformsnippet",
            name="subheading",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="qrcodefloatingsnippet",
            name="content",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="qrcodefloatingsnippet",
            name="heading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="qrcodesnippet",
            name="content",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="qrcodesnippet",
            name="heading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="simplerichtextpage",
            name="content",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="heading_text",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="mobile_message",
            field=springfield.cms.rich_text.RichTextField(
                default='<p data-block-key="abcdef">This experience is only available on desktop. Please open this page on your computer.</p>'
            ),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="post_download_instructions",
            field=springfield.cms.rich_text.RichTextField(
                blank=True,
                default="<p data-block-key='abcdef'>Return to this page after updating Firefox to unlock access to Smart Window BETA.</p>",
                help_text="Instructions displayed to the user for next steps after downloading Firefox.",
            ),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="privacy_notice",
            field=springfield.cms.rich_text.RichTextField(
                default='<p data-block-key="abcdef">I’m okay with Mozilla handling my info as explained in this '
                '<a href="https://www.mozilla.org/privacy/websites/">Privacy Notice</a>.</p>'
            ),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="subheading_text",
            field=springfield.cms.rich_text.RichTextField(),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="thank_you_heading",
            field=springfield.cms.rich_text.RichTextField(default='<p data-block-key="abcdef">You’re on the list!</p>'),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="thank_you_message",
            field=springfield.cms.rich_text.RichTextField(default='<p data-block-key="abcdef">Thank you!</p>'),
        ),
        migrations.AlterField(
            model_name="smartwindowpage",
            name="update_instructions",
            field=springfield.cms.rich_text.RichTextField(
                default="<p data-block-key='abcdef'>Before you can try Smart Window, you’ll need to download the latest version of Firefox.</p>",
                help_text="Instructions displayed to the user if they need to update Firefox before trying Smart Window.",
            ),
        ),
    ]
