# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-24 18:17

import django.db.models.deletion
from django.db import migrations, models

import wagtail.contrib.routable_page.models
import wagtail.fields

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0076_alter_smartwindowpage_post_download_instructions"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("slug", "locale"), ("translation_key", "locale")},
        ),
        migrations.CreateModel(
            name="BlogArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True, help_text="A short description used on the index page.")),
                ("featured", models.BooleanField(default=False, help_text="Check to set as a featured article on the index page.")),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "image_dark_mode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_dark_mode_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional dark mode mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional mobile variant of the article image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="blog_articles_tags", to="cms.tag")),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="blog_articles", to="cms.tag")),
            ],
            options={
                "verbose_name": "Blog Article Page",
                "verbose_name_plural": "Blog Article Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("page_heading", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "featured_articles",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Up to 8 featured articles shown at the top of the index page.", null=True
                    ),
                ),
                ("more_articles_heading", wagtail.fields.RichTextField(default='<p data-block-key="53ojj213">Read more</p>')),
                ("cards_lists", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
                "verbose_name_plural": "Blog Index Pages",
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page", models.Model),
        ),
    ]
