# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-24 14:36

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields

import springfield.cms.models.snippets


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0076_alter_smartwindowpage_post_download_instructions"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetAsDefaultSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("heading_text", models.CharField()),
                (
                    "not_firefox_content",
                    wagtail.fields.RichTextField(help_text="Content shown for non-Firefox users. A download button will be shown below it."),
                ),
                (
                    "not_default_desktop_content",
                    wagtail.fields.RichTextField(
                        help_text="Content shown for desktop users that haven't set the browser as default yet with instructions."
                    ),
                ),
                (
                    "not_default_android_content",
                    wagtail.fields.RichTextField(
                        help_text="Content shown for android users that haven't set the browser as default yet with instructions."
                    ),
                ),
                (
                    "not_default_ios_content",
                    wagtail.fields.RichTextField(
                        help_text="Content shown for ios users that haven't set the browser as default yet with instructions."
                    ),
                ),
                (
                    "success_content",
                    wagtail.fields.RichTextField(help_text="Content shown after user has successfully set Firefox as default browser."),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Set as Default Snippet",
                "verbose_name_plural": "Set as Default Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
    ]
