# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0077_alter_tag_unique_together_blogarticlepage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="featured",
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="display_image",
            field=models.BooleanField(default=False, help_text="Display image on the article's list"),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="view_all_label",
            field=models.CharField(default="View All Articles"),
        ),
    ]
