# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0078_editors_setasdefaultsnippet_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="setasdefaultsnippet",
            name="copy_success_label",
            field=models.CharField(
                default="Copied", help_text="Label displayed when the link is successfully copied to the clipboard.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="setasdefaultsnippet",
            name="copy_to_clipboard_label",
            field=models.CharField(
                default="Copy link to page", help_text="Label for the button that copies the page link to the clipboard.", max_length=255
            ),
        ),
    ]
