# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.11 on 2026-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0079_setasdefaultsnippet_copy_success_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="enable_marketing_attribution",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Enable marketing attribution for externally promoted pages."
                    " Adds the 'Share how you discovered Firefox' opt-out checkbox,"
                    " consent banner support for EU visitors, and stub attribution"
                    " for CPA tracking. Must not be used together with the 'Set as"
                    " default browser' checkbox on download buttons."
                ),
            ),
        ),
    ]
