# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0079_fix_compare_more_page_tree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articledetailpage",
            name="icon",
            field=models.CharField(blank=True, default="", help_text="Optional icon to display on icon article cards.", max_length=100),
        ),
    ]
