# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.12 on 2026-05-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0080_freeformpage2026_enable_marketing_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="show_navigation",
            field=models.BooleanField(
                default=True, help_text="If true, the navigation menu will be displayed on this page's header bar.", verbose_name="Show Navigation"
            ),
        ),
        migrations.AlterField(
            model_name="freeformpage2026",
            name="show_nav_cta",
            field=models.BooleanField(
                default=True,
                help_text="If true, the download button will appear in the navigation bar for this page. "
                "Only applicable if 'Show Navigation' is also enabled.",
                verbose_name="Show Navigation CTA",
            ),
        ),
        migrations.AlterField(
            model_name="freeformpage2026",
            name="show_pre_footer",
            field=models.BooleanField(
                default=True, help_text="If true, the page will display the default pre-footer section.", verbose_name="Show Pre-Footer"
            ),
        ),
    ]
