# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0083_update_banner_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="body_class",
            field=models.CharField(
                blank=True,
                help_text="Additional CSS classes to add to the body tag for this page.",
                max_length=255,
                verbose_name="Body Class",
            ),
        ),
    ]
