# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-14 21:47

from django.db import migrations

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0092_remove_blogarticlepage_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticlepage",
            name="description",
            field=springfield.cms.rich_text.RichTextField(blank=True, help_text="A short description used on the index page."),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="more_articles_heading",
            field=springfield.cms.rich_text.RichTextField(default='<p data-block-key="53ojj213">Read more</p>'),
        ),
    ]
