# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-18 22:49

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0093_alter_blogarticlepage_description_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("intro", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                ("content", springfield.cms.fields.StreamField(block_lookup={})),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Page",
                "verbose_name_plural": "Roadmap Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
