# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-26 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0094_alter_articledetailpage_icon"),
        ("cms", "0094_roadmap_page"),
    ]

    operations = []
