# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-05-28 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0096_migrate_media_content_intro_banner_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsnewpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="whatsnewpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FreeFormPage",
        ),
        migrations.DeleteModel(
            name="WhatsNewPage",
        ),
    ]
