# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-02 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0097_delete_freeformpage_whatsnewpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DownloadFirefoxCallToActionSnippet",
        ),
    ]
