# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-03 16:49

import uuid

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields

import springfield.cms.fields
import springfield.cms.models.snippets
import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0098_merge_20260602_2111"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PencilBannerSnippet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("title", springfield.cms.rich_text.RichTextField(help_text="Use italic text to insert a yellow pill.")),
                ("description", springfield.cms.rich_text.RichTextField()),
                ("link", models.URLField()),
                ("dismissable", models.BooleanField(default=False, help_text="Whether the banner can be dismissed by the user.")),
                ("settings", springfield.cms.fields.StreamField(blank=True, block_lookup={})),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pencil Banner Snippet",
                "verbose_name_plural": "Pencil Banner Snippets",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=(springfield.cms.models.snippets.FluentPreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PencilBannerPlacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pencil_banner_placements", to="cms.freeformpage2026"
                    ),
                ),
                ("snippet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="cms.pencilbannersnippet")),
            ],
            options={
                "verbose_name": "Pencil Banner Placement",
                "verbose_name_plural": "Pencil Banner Placements",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
