# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0099_pencilbannerplacement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pencilbannersnippet",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
