# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0100_alter_pencilbannersnippet_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="extra_js",
            field=models.CharField(
                blank=True,
                help_text="Additional JavaScript file to include for this page. Use the static bundle name (without the .js extension).",
                max_length=255,
                verbose_name="Extra JS",
            ),
        ),
    ]
