# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-09 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0096_flaredocsindexpage"),
        ("cms", "0101_freeformpage2026_extra_js"),
    ]

    operations = []
