# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0101_freeformpage2026_extra_js"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="body_class",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Additional CSS class to add to the body tag for this page, to be used for light theming. "
                    "The page will also inject <this>.css, so ensure that exists before using this field."
                ),
                max_length=255,
                verbose_name="Body Class",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="extra_js",
            field=models.CharField(
                blank=True,
                help_text="Additional JavaScript file to include for this page. Use the static bundle name (without the .js extension).",
                max_length=255,
                verbose_name="Extra JS",
            ),
        ),
    ]
