# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-11 19:15

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields
import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0102_whatsnewpage2026_body_class_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "form_fields",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Define the form fields that will appear on the contact page.", null=True
                    ),
                ),
                ("to_email_address", models.EmailField(blank=True, help_text="Email address where form submissions will be sent.", max_length=254)),
                (
                    "basket_api_path",
                    models.CharField(
                        blank=True,
                        help_text="Basket API path (e.g. /api/v1/contact/). Concatenated with settings.BASKET_URL on submission. "
                        "Required if Email Address is not set.",
                        max_length=255,
                    ),
                ),
                (
                    "thank_you_message",
                    springfield.cms.rich_text.RichTextField(
                        blank=True, help_text="Message shown in place of the form after a successful submission. Required if Redirect To is not set."
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                (
                    "redirect_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Page to redirect to after a successful form submission (e.g. a thank-you page).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page",
                "verbose_name_plural": "Contact Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
