# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0102_whatsnewpage2026_body_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="marketing_attribution_mode",
            field=models.CharField(
                blank=True,
                choices=[("", "Disabled"), ("enabled", "Enabled (always promoted)"), ("param", "Enabled only when ?promoted=1 in URL")],
                help_text=(
                    "Controls whether this page is treated as an externally-promoted "
                    "landing page (adds the 'Share how you discovered Firefox' opt-out "
                    "checkbox, consent banner support for EU visitors, and stub "
                    "attribution for CPA tracking). Use 'Enabled only when ?promoted=1' "
                    "for landing pages that serve both organic and paid traffic — the "
                    "promoted treatment is only rendered for visitors arriving via the "
                    "?promoted=1 query param. Must not be used together with the "
                    "'Set as default browser' checkbox on download buttons."
                ),
                max_length=20,
                verbose_name="Marketing Attribution Mode",
            ),
        ),
        migrations.AlterField(
            model_name="freeformpage2026",
            name="enable_marketing_attribution",
            field=models.BooleanField(default=False),
        ),
    ]
