# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-12 23:47

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0103_contactpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleDetailPagePencilBannerPlacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pencil_banner_placements", to="cms.articledetailpage"
                    ),
                ),
                ("snippet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="cms.pencilbannersnippet")),
            ],
            options={
                "verbose_name": "Article Detail Page Pencil Banner Placement",
                "verbose_name_plural": "Article Detail Page Pencil Banner Placements",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleThemePagePencilBannerPlacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pencil_banner_placements", to="cms.articlethemepage"
                    ),
                ),
                ("snippet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="cms.pencilbannersnippet")),
            ],
            options={
                "verbose_name": "Article Theme Page Pencil Banner Placement",
                "verbose_name_plural": "Article Theme Page Pencil Banner Placements",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePagePencilBannerPlacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pencil_banner_placements", to="cms.homepage"
                    ),
                ),
                ("snippet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="cms.pencilbannersnippet")),
            ],
            options={
                "verbose_name": "Home Page Pencil Banner Placement",
                "verbose_name_plural": "Home Page Pencil Banner Placements",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
