# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-11 02:30

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0103_contactpage"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="basket_api_path",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Basket API path (e.g. /api/v1/contact/). Concatenated with settings.BASKET_URL"
                    " on submission. Required if Email Address is not set."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="thank_you_message",
            field=springfield.cms.rich_text.RichTextField(
                blank=True, help_text="Message shown in place of the form after a successful submission. Required if Redirect To is not set."
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="redirect_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Page to redirect to after a successful form submission (e.g. a thank-you page).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="to_email_address",
            field=models.EmailField(blank=True, help_text="Email address where form submissions will be sent.", max_length=254),
        ),
    ]
