# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-11 18:21

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0104_contactpage_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="subheading",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="intro",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
