# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-16 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0103_merge_20260610_0913"),
        ("cms", "0104_articledetailpagepencilbannerplacement_and_more"),
    ]

    operations = []
