# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-06-23 20:27

from django.db import migrations

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0109_flaredocsindexpage_to_freeformpage2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="docs",
            field=springfield.cms.rich_text.RichTextField(
                blank=True,
                help_text=(
                    "Optional documentation about this page. Only used by Flare Docs demo pages "
                    "to describe the block(s) or snippet(s) being demonstrated — leave blank on "
                    "production pages."
                ),
            ),
        ),
    ]
