# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-06-29 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0109_migrate_all_button_labels"),
        ("cms", "0110_freeformpage2026_docs"),
    ]

    operations = []
