# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-03 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0111_merge_20260629_1539"),
        ("cms", "0111_remove_stale_contenttypes"),
    ]

    operations = []
