# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0111_remove_stale_contenttypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("", "Firefox"), ("enterprise", "Enterprise")],
                default="",
                help_text="The theme to use for this page. This overrides the page's CSS, navigation, footer, logo and other visual elements.",
                max_length=20,
                verbose_name="Theme",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("", "Firefox"), ("enterprise", "Enterprise")],
                default="",
                help_text="The theme to use for this page. This overrides the page's CSS, navigation, footer, logo and other visual elements.",
                max_length=20,
                verbose_name="Theme",
            ),
        ),
    ]
