# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0112_freeformpage2026_theme_whatsnewpage2026_theme"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Human-readable name shown in the admin (e.g. 'Lapsed users → welcomeback').", max_length=255)),
                ("priority", models.IntegerField(default=100, help_text="Lower numbers evaluate first. Ties broken by rule ID.")),
                (
                    "condition",
                    models.JSONField(
                        blank=True, default=dict, help_text='Structured rule condition, e.g. {"signal": "lapsed_user", "equals": true}.'
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("live", "Live"), ("retired", "Retired")],
                        default="draft",
                        help_text="Only 'Live' rules are evaluated by the resolver.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_page",
                    models.ForeignKey(
                        help_text="The canonical page this rule attaches to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_rules_as_parent",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "target_page",
                    models.ForeignKey(
                        help_text="The variant page to route matching users to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_rules_as_target",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Rule",
                "verbose_name_plural": "Routing Rules",
                "ordering": ["parent_page", "priority", "id"],
                "indexes": [models.Index(fields=["parent_page", "status", "priority"], name="cms_routing_parent__7b8da7_idx")],
            },
        ),
    ]
