# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-08 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0112_freeformpage2026_theme_whatsnewpage2026_theme"),
        ("cms", "0112_merge_20260702_2106"),
    ]

    operations = []
