# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# ruff: noqa: E501

# Generated by Django 5.2.15 on 2026-07-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0112_freeformpage2026_theme_whatsnewpage2026_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartwindowpage",
            name="show_smart_window_button",
            field=models.CharField(
                choices=[("all", "Show to all users"), ("allowed_territories", "US, Canada, and France only"), ("never", "Never show to any users")],
                default="allowed_territories",
                help_text="Controls whether the 'Try Smart Window' button is shown on the page. When not available, the Waitlist form is shown instead.",
                max_length=20,
            ),
        ),
    ]
