# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-09 00:33

import django.db.models.deletion
from django.db import migrations

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0113_routingrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="routingrule",
            options={"ordering": ["parent_page", "priority", "id"], "verbose_name": "User Routing rule", "verbose_name_plural": "User Routing rules"},
        ),
        migrations.AlterField(
            model_name="routingrule",
            name="parent_page",
            field=modelcluster.fields.ParentalKey(
                help_text="The canonical page this rule attaches to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_rules",
                to="cms.whatsnewpage2026",
            ),
        ),
    ]
