# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-07-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0114_merge_20260714_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="pre_footer_image",
            field=models.CharField(
                choices=[
                    ("kit", "Show Kit on Newsletter form"),
                    ("globe", "Show globe pictogram on Newsletter form"),
                    ("none", "Hide Newsletter form image"),
                ],
                default="kit",
                help_text="Image shown alongside the pre-footer newsletter form.",
                max_length=20,
                verbose_name="Pre-footer options",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="pre_footer_image",
            field=models.CharField(
                choices=[
                    ("kit", "Show Kit on Newsletter form"),
                    ("globe", "Show globe pictogram on Newsletter form"),
                    ("none", "Hide Newsletter form image"),
                ],
                default="kit",
                help_text="Image shown alongside the pre-footer newsletter form.",
                max_length=20,
                verbose_name="Pre-footer options",
            ),
        ),
    ]
