# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-09 01:02

from django.db import migrations, models

import springfield.cms.models.routing


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0114_alter_routingrule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routingrule",
            name="condition",
        ),
        migrations.AddField(
            model_name="routingrule",
            name="expected_value",
            field=models.CharField(
                blank=True,
                help_text=(
                    "The value the signal must have for this rule to match. "
                    "Booleans: 'true' or 'false'. Integers: a number. "
                    "Strings: the literal value (e.g. 'available' for ai_controls)."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="operator",
            field=models.CharField(
                choices=[("equals", "equals")], default="equals", help_text="How the signal's value is compared to the expected value.", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="signal_name",
            field=models.CharField(
                blank=True,
                choices=springfield.cms.models.routing._signal_choices,
                help_text="Which browser or server signal this rule checks.",
                max_length=64,
            ),
        ),
    ]
