# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-09 06:07
# Hand-edited to add a data migration between the AddField and RemoveField
# steps so any locally-authored RoutingRule instances survive the shape
# change (expected_value single string → expected_values list-in-text,
# operator 'equals' → 'is').

from django.db import migrations, models


def forwards_migrate_data(apps, schema_editor):
    """Copy scalar ``expected_value`` into the new ``expected_values`` TextField
    and rename ``operator='equals'`` to ``operator='is'``."""
    RoutingRule = apps.get_model("cms", "RoutingRule")
    for rule in RoutingRule.objects.all():
        old_value = getattr(rule, "expected_value", "") or ""
        rule.expected_values = old_value
        if rule.operator == "equals":
            rule.operator = "is"
        rule.save(update_fields=["expected_values", "operator"])


def backwards_migrate_data(apps, schema_editor):
    """Best-effort reverse: take the first line of expected_values as the
    single expected_value, and rename operator 'is' → 'equals'."""
    RoutingRule = apps.get_model("cms", "RoutingRule")
    for rule in RoutingRule.objects.all():
        values = (rule.expected_values or "").splitlines()
        rule.expected_value = values[0] if values else ""
        if rule.operator == "is":
            rule.operator = "equals"
        rule.save(update_fields=["expected_value", "operator"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0115_remove_routingrule_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routingrule",
            name="expected_values",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "One or more values, one per line (commas also accepted). "
                    "For enum-valued signals, values must match the exact allowed set "
                    "(check the signal's help entry). Booleans: 'true' or 'false'. "
                    "Integers: a number."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="routingrule",
            name="operator",
            field=models.CharField(
                choices=[("is", "is"), ("is_not", "is not")],
                default="is",
                help_text="`is` matches when the signal is one of the values below; `is not` matches when it isn't.",
                max_length=16,
            ),
        ),
        migrations.RunPython(forwards_migrate_data, backwards_migrate_data),
        migrations.RemoveField(
            model_name="routingrule",
            name="expected_value",
        ),
    ]
