# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.14 on 2026-07-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0115_navigationsnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="articleindexpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="articlethemepage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="flaredocsindexpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="roadmappage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="custom_navigation",
            field=models.ForeignKey(
                blank=True,
                help_text="Override the page header navigation with this menu. "
                "Falls back to the default navigation if unset or unavailable in the active locale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.navigationsnippet",
            ),
        ),
    ]
