# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-16 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0115_migrate_card_blocks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articledetailpage",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                help_text="A pictogram image used in article cards.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="sticker_dark_mode",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode variant of the pictogram.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="sticker_dark_mode_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional dark mode mobile variant of the pictogram.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AlterField(
            model_name="articledetailpage",
            name="sticker_mobile",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional mobile variant of the pictogram.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AlterField(
            model_name="articleindexpage",
            name="index_card_type",
            field=models.CharField(
                choices=[("sticker_card", "Pictogram card"), ("outline_card", "Outline card"), ("illustration_card", "Illustration card")],
                default="sticker_card",
                help_text="Controls the card style used in the article listing.",
                max_length=20,
            ),
        ),
    ]
