# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0120_author_blogarticlepage_author"),
        ("cms", "0120_referralgetfirefoxpage_referralhubpage"),
    ]

    operations = []
