# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0120_referralgetfirefoxpage_referralhubpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="body_class",
            field=models.CharField(
                blank=True,
                help_text="Additional CSS class to add to the body tag for this page, to be used for light theming. The page will also inject "
                "<this>.css, so ensure that exists before using this field.",
                max_length=255,
                verbose_name="Body Class",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="extra_js",
            field=models.CharField(
                blank=True,
                help_text="Additional JavaScript file to include for this page. Use the static bundle name (without the .js extension).",
                max_length=255,
                verbose_name="Extra JS",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[("", "Firefox"), ("enterprise", "Enterprise")],
                default="",
                help_text="The theme to use for this page. This overrides the page's CSS, navigation, footer, logo and other visual elements.",
                max_length=20,
                verbose_name="Theme",
            ),
        ),
    ]
