# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0120_referralgetfirefoxpage_referralhubpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadpage",
            name="floating_qr_content",
            field=models.CharField(
                blank=True, help_text="Override the content of the Floating QR code snippet.", verbose_name="Override Floating QR Code Content"
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="floating_qr_default_open",
            field=models.BooleanField(
                blank=True,
                help_text="Override the default open state of the Floating QR code snippet.",
                null=True,
                verbose_name="Override Floating QR Code Default Open",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="floating_qr_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Override with an uploaded QR code image. Takes priority over the URL.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
                verbose_name="Override Floating QR Code Image",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="floating_qr_title",
            field=models.CharField(
                blank=True, help_text="Override the title of the Floating QR code snippet.", verbose_name="Override Floating QR Code Title"
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="floating_qr_url",
            field=models.CharField(
                blank=True,
                help_text="Override the snippet URL. A QR code will be generated from this. Not used if an override image is set.",
                verbose_name="Override Floating QR Code URL",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="show_floating_qr_code_snippet",
            field=models.BooleanField(
                default=False,
                help_text="If true, an updated floating QR code snippet will be displayed on the page.",
                verbose_name="Show Floating QR Code Snippet",
            ),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="show_qr_code_snippet",
            field=models.BooleanField(default=False, help_text="If true, a floating QR code snippet will be displayed on the page."),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="floating_qr_content",
            field=models.CharField(
                blank=True, help_text="Override the content of the Floating QR code snippet.", verbose_name="Override Floating QR Code Content"
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="floating_qr_title",
            field=models.CharField(
                blank=True, help_text="Override the title of the Floating QR code snippet.", verbose_name="Override Floating QR Code Title"
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="floating_qr_content",
            field=models.CharField(
                blank=True, help_text="Override the content of the Floating QR code snippet.", verbose_name="Override Floating QR Code Content"
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="floating_qr_title",
            field=models.CharField(
                blank=True, help_text="Override the title of the Floating QR code snippet.", verbose_name="Override Floating QR Code Title"
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="floating_qr_content",
            field=models.CharField(
                blank=True, help_text="Override the content of the Floating QR code snippet.", verbose_name="Override Floating QR Code Content"
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="floating_qr_title",
            field=models.CharField(
                blank=True, help_text="Override the title of the Floating QR code snippet.", verbose_name="Override Floating QR Code Title"
            ),
        ),
    ]
