# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-20 23:15

from django.db import migrations, models

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0121_referralhubpage_heading_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralhubpage",
            name="invite_details",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="referralhubpage",
            name="invite_heading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="referralhubpage",
            name="invite_label",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="referralhubpage",
            name="stats_heading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="referralhubpage",
            name="stats_label",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="referralhubpage",
            name="stats_subheading",
            field=springfield.cms.rich_text.RichTextField(blank=True),
        ),
    ]
