# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-23 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0121_contactpage_body_class_contactpage_extra_js_and_more"),
        ("cms", "0121_merge_20260723_0243"),
    ]

    operations = []
