# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-30 21:04

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields

import springfield.cms.routing.models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0124_articledetailpage_internal_title_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "routing_paused",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, routing is bypassed and canonical content is served directly. Previews still work.",
                        verbose_name="Pause routing",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="routing_config", to="wagtailcore.page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing configuration",
                "verbose_name_plural": "Routing configurations",
            },
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name="routing_rules", to="wagtailcore.page"),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The page to route matching users to. Must be a descendant of this page.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Target page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this rule, shown in listings. Falls back to a summary of its conditions.",
                        max_length=255,
                        verbose_name="Rule name",
                    ),
                ),
                (
                    "match_all",
                    models.BooleanField(
                        default=False,
                        help_text="Route every triggered visitor to the target (no conditions). Matches before any rule below it.",
                        verbose_name="Match all triggered visitors",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing rule",
                "verbose_name_plural": "Routing rules",
                "ordering": ["sort_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoutingCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("signal", models.CharField(choices=springfield.cms.routing.models.signal_choices, max_length=100, verbose_name="Signal")),
                ("operator", models.CharField(choices=springfield.cms.routing.models.operator_choices, max_length=20, verbose_name="Operator")),
                (
                    "expected_value",
                    models.TextField(
                        verbose_name="Expected value",
                    ),
                ),
                (
                    "rule",
                    modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="cms.routingrule"),
                ),
            ],
            options={
                "verbose_name": "Condition",
                "verbose_name_plural": "Conditions",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
