# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0125_referralhubpage_extra_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeformpage2026",
            name="floating_qr_open_behavior",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open on page load"), ("closed", "Closed"), ("delayed", "Closed, then opens automatically")],
                default="",
                help_text="Leave blank to inherit the snippet's setting.",
                max_length=16,
                verbose_name="Override Floating QR Code Open Behavior",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage2026",
            name="floating_qr_open_delay_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Milliseconds before the snippet opens. Leave blank to inherit the snippet's setting.",
                null=True,
                verbose_name="Override Floating QR Code Open Delay",
            ),
        ),
        migrations.AddField(
            model_name="qrcodefloatingsnippet",
            name="open_behavior",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open on page load"), ("closed", "Closed"), ("delayed", "Closed, then opens automatically")],
                default="",
                help_text="How the snippet starts. Leave blank to use the previous open/closed setting.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="qrcodefloatingsnippet",
            name="open_delay_ms",
            field=models.PositiveIntegerField(
                default=3000,
                help_text="Delay before the snippet opens, in milliseconds (3000 = 3 seconds). Only used for the auto-open behavior.",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="floating_qr_open_behavior",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open on page load"), ("closed", "Closed"), ("delayed", "Closed, then opens automatically")],
                default="",
                help_text="Leave blank to inherit the snippet's setting.",
                max_length=16,
                verbose_name="Override Floating QR Code Open Behavior",
            ),
        ),
        migrations.AddField(
            model_name="thankspage",
            name="floating_qr_open_delay_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Milliseconds before the snippet opens. Leave blank to inherit the snippet's setting.",
                null=True,
                verbose_name="Override Floating QR Code Open Delay",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="floating_qr_open_behavior",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open on page load"), ("closed", "Closed"), ("delayed", "Closed, then opens automatically")],
                default="",
                help_text="Leave blank to inherit the snippet's setting.",
                max_length=16,
                verbose_name="Override Floating QR Code Open Behavior",
            ),
        ),
        migrations.AddField(
            model_name="whatsnewpage2026",
            name="floating_qr_open_delay_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Milliseconds before the snippet opens. Leave blank to inherit the snippet's setting.",
                null=True,
                verbose_name="Override Floating QR Code Open Delay",
            ),
        ),
    ]
