# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-04 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0126_blogtopic"),
    ]

    operations = [
        # topic_id currently holds cms_tag primary keys. Dropping the column and
        # adding a fresh nullable one avoids validating those stale ids against
        # cms_blogtopic, and keeps every article row in place.
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="topic",
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_articles",
                to="cms.blogtopic",
            ),
        ),
    ]
