# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 16:11

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0128_editors_moderators_blogtopic_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="featured_topics",
            field=springfield.cms.fields.StreamField(
                blank=True,
                block_lookup={},
                help_text="Up to 8 topics shown at the top of the index page. If empty, the topics with the most articles are shown.",
                null=True,
            ),
        ),
    ]
