# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 21:33

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0129_blogindexpage_featured_topics"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTopicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "internal_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Editor-only label for organizing pages in the CMS. Not shown to the public; the public title is used when blank.",
                        max_length=255,
                    ),
                ),
                (
                    "stub_attr_utm_campaign_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("default", "Default (used if no utm_campaign in URL)"),
                            ("override", "Override (replaces utm_campaign from URL, respects cookie)"),
                            ("force", "Force (replaces everything, clears attribution cookie)"),
                        ],
                        help_text="Controls how the campaign value is applied to download attribution.",
                        max_length=20,
                        verbose_name="Stub Attribution Mode",
                    ),
                ),
                (
                    "stub_attr_utm_campaign_value",
                    models.CharField(
                        blank=True,
                        help_text="The campaign value to use for stub attribution. Only used if a mode is selected above.",
                        max_length=255,
                        verbose_name="Stub Attribution Campaign Value",
                    ),
                ),
                ("page_heading", springfield.cms.fields.StreamField(blank=True, block_lookup={})),
                (
                    "featured_articles",
                    springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Up to 4 featured articles shown at the top. These are left out of the list below."
                    ),
                ),
                (
                    "custom_navigation",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Override the page header navigation with this menu. If unset, the page inherits its nearest ancestor's "
                            "custom navigation, then the site default navigation, then the built-in navigation."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.navigationsnippet",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="topic_pages", to="cms.blogtopic")),
            ],
            options={
                "verbose_name": "Blog Topic Page",
                "verbose_name_plural": "Blog Topic Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
