# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-10 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0129_blogindexpage_featured_topics"),
        ("cms", "0129_referralgetfirefoxpage_lower_content_and_more"),
    ]

    operations = []
