# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 15:59

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0132_blogtag_taggedblogarticle"),
    ]

    operations = [
        # The old tags M2M and the new taggit relation live in different tables, so the
        # column-less AddField is safe: RemoveField drops cms_blogarticlepage_tags and with
        # it every existing tag assignment, which is intended — see the design doc.
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="tags",
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="tags",
            field=springfield.cms.fields.LocalizedClusterTaggableManager(
                blank=True, help_text="A comma-separated list of tags.", through="cms.TaggedBlogArticle", to="cms.BlogTag", verbose_name="Tags"
            ),
        ),
    ]
