# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 15:59

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0133_blogtag_taggedblogarticle"),
    ]

    operations = [
        # Drop the existing tags field and add a new one with the updated LocalizedClusterTaggableManager.
        # The operation is safe since there are no blog articles in the database yet.
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="tags",
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="tags",
            field=springfield.cms.fields.LocalizedClusterTaggableManager(
                blank=True, help_text="A comma-separated list of tags.", through="cms.TaggedBlogArticle", to="cms.BlogTag", verbose_name="Tags"
            ),
        ),
    ]
