# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-07 22:31

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0134_blogauthor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogArticleAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.blogauthor")),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="article_authors", to="cms.blogarticlepage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Article Author",
                "verbose_name_plural": "Blog Article Authors",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
