# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-07 22:02

import uuid

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.rich_text


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0135_editors_moderators_blogtag_permissions"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("live", models.BooleanField(default=True, editable=False, verbose_name="live")),
                ("has_unpublished_changes", models.BooleanField(default=False, editable=False, verbose_name="has unpublished changes")),
                ("first_published_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="first published at")),
                ("last_published_at", models.DateTimeField(editable=False, null=True, verbose_name="last published at")),
                ("go_live_at", models.DateTimeField(blank=True, null=True, verbose_name="go live date/time")),
                ("expire_at", models.DateTimeField(blank=True, null=True, verbose_name="expiry date/time")),
                ("expired", models.BooleanField(default=False, editable=False, verbose_name="expired")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("bio", springfield.cms.rich_text.RichTextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cms.springfieldimage"
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale", verbose_name="locale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Author",
                "verbose_name_plural": "Blog Authors",
                "abstract": False,
                "unique_together": {("slug", "locale"), ("translation_key", "locale")},
            },
        ),
    ]
