# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0135_editors_moderators_blogtag_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="basket_api_path",
            field=models.CharField(
                blank=True,
                choices=[("/api/v1/contact/enterprise/", "/api/v1/contact/enterprise/")],
                help_text="Basket endpoint the form posts to. Required if Email Address is unset. Form fields must match what it accepts.",
                max_length=255,
            ),
        ),
    ]
