# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-10 22:14

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0137_editors_moderators_blogauthor_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogarticlepage",
            name="display_image",
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="hero_style",
            field=models.CharField(
                choices=[
                    ("standard_image", "Standard image"),
                    ("large_image", "Large featured image"),
                    ("text_only", "No image, text only"),
                    ("video", "Featured video"),
                ],
                default="standard_image",
                help_text="Layout for the article header.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="hero_video",
            field=springfield.cms.fields.StreamField(
                blank=True, block_lookup={}, help_text="Video shown in the header when the hero style is “Featured video”.", null=True
            ),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="hide_dates",
            field=models.BooleanField(default=False, help_text="Hide the published and updated dates on this article."),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional image for article cards and lists. Falls back to the featured image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cms.springfieldimage",
            ),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="updated_date",
            field=models.DateField(blank=True, help_text="Shown as “Last updated on …”. Leave empty to show only the published date.", null=True),
        ),
    ]
