# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-14 01:15

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0139_blogarticlepage_hero_dates_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticlepage",
            name="bottom_banner",
            field=springfield.cms.fields.StreamField(
                blank=True, block_lookup={}, help_text="Optional banner to be displayed at the bottom of the article content."
            ),
        ),
    ]
