# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-14 17:19

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0141_blogindexpage_feed_exclusions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="featured_articles",
            field=springfield.cms.fields.StreamField(
                blank=True,
                block_lookup={},
                help_text="Up to 4 featured articles shown at the top of the index page.",
                null=True,
            ),
        ),
    ]
