# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-19 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0140_merge_20260818_1955"),
        ("cms", "0142_remove_blogindexpage_cards_lists_and_more"),
    ]

    operations = []
