# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-14 18:02

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0142_alter_blogindexpage_featured_articles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogindexpage",
            name="cards_lists",
        ),
        migrations.RemoveField(
            model_name="blogindexpage",
            name="more_articles_heading",
        ),
        migrations.RemoveField(
            model_name="blogindexpage",
            name="view_all_label",
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="article_sections",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
