# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-19 03:40

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0143_merge_20260818_2040"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="blogarticlepage",
                    name="bottom_banner",
                    field=springfield.cms.fields.StreamField(
                        blank=True, block_lookup={}, help_text="Optional banner to be displayed at the bottom of the article content."
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE cms_blogarticlepage ADD COLUMN IF NOT EXISTS bottom_banner jsonb DEFAULT '[]'",
                    reverse_sql="ALTER TABLE cms_blogarticlepage DROP COLUMN IF EXISTS bottom_banner",
                ),
            ],
        ),
    ]
