# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_impact_dash_locked_content"),
        ("cms", "0145_migrate_tab_image_to_media"),
    ]

    operations = []
