# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-01 22:44

from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0145_migrate_tab_image_to_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticlepage",
            name="hide_related",
            field=models.BooleanField(default=False, help_text="Hide the Related Articles section on this article."),
        ),
        migrations.AddField(
            model_name="blogarticlepage",
            name="related_articles",
            field=springfield.cms.fields.StreamField(
                blank=True,
                block_lookup={},
                help_text=(
                    "Up to 4 related articles shown at the bottom. Remaining empty slots are filled with articles that "
                    "match by topic and tag, then topic, then tag, up to 4."
                ),
            ),
        ),
    ]
