# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-04 21:07

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0148_merge_20260902_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="thankspage",
            name="notification",
            field=springfield.cms.fields.StreamField(
                blank=True, block_lookup={}, help_text="Up to two notifications shown above the page's main content.", null=True
            ),
        ),
    ]
