# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-05 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0148_migrate_qr_open_behavior"),
        ("cms", "0149_smartwindowpage_enable_marketing_attribution"),
    ]

    operations = []
