# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-05 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0149_thankspage_notification"),
        ("cms", "0150_merge_20260904_1724"),
    ]

    operations = []
