# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-09-10 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0151_merge_20260904_2119"),
        ("cms", "0151_sync_whats_new_version_translations"),
    ]

    operations = []
