# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Removes blog models from the cms app's migration state only.
# `blog.0001`, `blog.0002`, and `blog.0003` complete the rest
# of the `blog` model migration.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0151_sync_whats_new_version_translations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="custom_navigation",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="image",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="image_dark_mode",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="image_dark_mode_mobile",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="image_mobile",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="listing_image",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="og_image",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="page_ptr",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="tags",
                ),
                migrations.RemoveField(
                    model_name="blogarticlepage",
                    name="topic",
                ),
                migrations.RemoveField(
                    model_name="taggedblogarticle",
                    name="content_object",
                ),
                migrations.AlterUniqueTogether(
                    name="blogauthor",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="blogauthor",
                    name="image",
                ),
                migrations.RemoveField(
                    model_name="blogauthor",
                    name="latest_revision",
                ),
                migrations.RemoveField(
                    model_name="blogauthor",
                    name="live_revision",
                ),
                migrations.RemoveField(
                    model_name="blogauthor",
                    name="locale",
                ),
                migrations.RemoveField(
                    model_name="blogindexpage",
                    name="custom_navigation",
                ),
                migrations.RemoveField(
                    model_name="blogindexpage",
                    name="og_image",
                ),
                migrations.RemoveField(
                    model_name="blogindexpage",
                    name="page_ptr",
                ),
                migrations.AlterUniqueTogether(
                    name="blogtag",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="blogtag",
                    name="latest_revision",
                ),
                migrations.RemoveField(
                    model_name="blogtag",
                    name="live_revision",
                ),
                migrations.RemoveField(
                    model_name="blogtag",
                    name="locale",
                ),
                migrations.RemoveField(
                    model_name="taggedblogarticle",
                    name="tag",
                ),
                migrations.AlterUniqueTogether(
                    name="blogtopic",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="blogtopic",
                    name="latest_revision",
                ),
                migrations.RemoveField(
                    model_name="blogtopic",
                    name="live_revision",
                ),
                migrations.RemoveField(
                    model_name="blogtopic",
                    name="locale",
                ),
                migrations.RemoveField(
                    model_name="blogtopicpage",
                    name="topic",
                ),
                migrations.RemoveField(
                    model_name="blogtopicpage",
                    name="custom_navigation",
                ),
                migrations.RemoveField(
                    model_name="blogtopicpage",
                    name="og_image",
                ),
                migrations.RemoveField(
                    model_name="blogtopicpage",
                    name="page_ptr",
                ),
                migrations.DeleteModel(
                    name="BlogArticleAuthor",
                ),
                migrations.DeleteModel(
                    name="BlogArticlePage",
                ),
                migrations.DeleteModel(
                    name="BlogAuthor",
                ),
                migrations.DeleteModel(
                    name="BlogIndexPage",
                ),
                migrations.DeleteModel(
                    name="BlogTag",
                ),
                migrations.DeleteModel(
                    name="TaggedBlogArticle",
                ),
                migrations.DeleteModel(
                    name="BlogTopic",
                ),
                migrations.DeleteModel(
                    name="BlogTopicPage",
                ),
            ],
            database_operations=[],
        ),
    ]
