# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0152_merge_20260910_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="springfieldimage",
            name="is_decorative",
            field=models.BooleanField(
                default=False,
                help_text="Purely visual, with nothing a description could convey. Rendered with an empty alt attribute, so screen readers skip it.",
                verbose_name="Image is decorative",
            ),
        ),
    ]
