# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-15 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0152_merge_20260910_1400"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="document_download",
            field=models.ForeignKey(
                blank=True,
                help_text="File offered for download alongside the thank you message, once the form has been submitted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="document_download_label",
            field=models.CharField(
                blank=True, help_text="Fallback text for the download link in case JavaScript is disabled. Required if a file is set.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="basket_api_path",
            field=models.CharField(
                blank=True,
                choices=[("/api/v1/contact/enterprise/", "/api/v1/contact/enterprise/"), ("/api/v1/contact/basic/", "/api/v1/contact/basic/")],
                help_text="Basket endpoint the form posts to. Required if Email Address is unset. Form fields must match what it accepts.",
                max_length=255,
            ),
        ),
    ]
