# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-23 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0155_create_main_navigation_snippet"),
        ("cms", "0155_springfieldimage_is_decorative"),
    ]

    operations = []
