# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0155_springfieldimage_is_decorative"),
    ]

    operations = [
        migrations.AddField(
            model_name="articledetailpage",
            name="featured_image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
        migrations.AddField(
            model_name="articledetailpage",
            name="image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
        migrations.AddField(
            model_name="downloadpage",
            name="featured_image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
        migrations.AddField(
            model_name="smartwindowpage",
            name="image_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
    ]
