# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0156_articledetailpage_featured_image_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsnippet",
            name="logo_alt",
            field=models.CharField(blank=True, help_text="Text for screen readers describing the image.", max_length=255),
        ),
    ]
