# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0157_contactpage_document_download_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="basket_form_id",
            field=models.CharField(blank=True, help_text="Form id basket routes the submission by. Required for /api/v1/intake/.", max_length=255),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="basket_api_path",
            field=models.CharField(
                blank=True,
                choices=[
                    ("/api/v1/contact/enterprise/", "/api/v1/contact/enterprise/"),
                    ("/api/v1/contact/basic/", "/api/v1/contact/basic/"),
                    ("/api/v1/intake/", "/api/v1/intake/"),
                ],
                help_text="Basket endpoint the form posts to. Required if Email Address is unset. Form fields must match what it accepts.",
                max_length=255,
            ),
        ),
    ]
