# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-29 18:43

import django.db.models.deletion
from django.db import migrations, models

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0158_contactpage_basket_form_id_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareFirefoxPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "internal_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Editor-only label for organizing pages in the CMS. Not shown to the public; the public title is used when blank.",
                        max_length=255,
                    ),
                ),
                ("upper_content", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                ("lower_content", springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True)),
                (
                    "custom_navigation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override the page header navigation with this menu. If unset, the page "
                        "inherits its nearest ancestor's custom navigation, then the site default "
                        "navigation, then the built-in navigation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cms.navigationsnippet",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed when this page is shared on social media. Recommended size: 1200×630 pixels (PNG).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cms.springfieldimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Firefox Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
