# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.17 on 2026-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0158_contactpage_basket_form_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="springfieldimage",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
    ]
