# Generated by Django 5.2 on 2025-05-22 15:35

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasenotes', '0002_auto_20200122_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(help_text='3166-1-alpha-2 code', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_country_name_for_code')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('product', models.CharField(choices=[('Firefox', 'Firefox'), ('Firefox for Android', 'Firefox for Android'), ('Firefox for iOS', 'Firefox for iOS'), ('Firefox Extended Support Release', 'Firefox Extended Support Release'), ('Thunderbird', 'Thunderbird')], max_length=255)),
                ('channel', models.CharField(choices=[('Nightly', 'Nightly'), ('Beta', 'Beta'), ('Release', 'Release'), ('ESR', 'ESR')], max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Note: If checked, these Release Notes will be visible on www.firefox.com')),
                ('bug_list', models.TextField(blank=True)),
                ('bug_search_url', models.CharField(blank=True, max_length=2000)),
                ('system_requirements', models.TextField(blank=True)),
                ('reviewed_by_release_manager', models.BooleanField(default=False, help_text='Purely a visual indicator in the admin - does not show on firefox.com', null=True)),
            ],
            options={
                'ordering': ['-release_date'],
                'get_latest_by': 'modified',
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('bug', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_known_issue', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, choices=[('New', 'New'), ('Changed', 'Changed'), ('HTML5', 'HTML5'), ('Feature', 'Feature'), ('Language', 'Language'), ('Developer', 'Developer'), ('Enterprise', 'Enterprise'), ('Fixed', 'Fixed'), ('Community', 'Community')], max_length=255)),
                ('sort_num', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('progressive_rollout', models.BooleanField(default=False)),
                ('relevant_countries', models.ManyToManyField(blank=True, help_text="Select the countries where this Note applies, as part of a progressive rollout. This info will only be shown on the Release page if 'Progressive rollout', above, is ticked.", to='releasenotes.country')),
                ('fixed_in_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_note_set', to='releasenotes.release')),
                ('releases', models.ManyToManyField(blank=True, to='releasenotes.release')),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
