# Generated by Django 5.2 on 2025-05-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releasenotes', '0004_data_bootstrap_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRelease',
        ),
    ]
