# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import re

_SIZE_SUFFIX_RE = re.compile(r"-\d+$")


def icon_css_name(stem):
    """Strip trailing size suffix from an icon filename stem.

    'activity-16'        → 'activity'
    'arrow-clockwise-16' → 'arrow-clockwise'
    'add-circle-fill-16' → 'add-circle-fill'
    """
    return _SIZE_SUFFIX_RE.sub("", stem)


# some icon paths produce the same CSS name as another icon.
# For these specific files, icon_value_fn returns the relative path instead of
# the CSS name to avoid the collision.
_COLLIDING_PATHS = frozenset(
    {
        "mobile-24/app-menu-more-options/app-menu-space-24",
        "mobile-24/arrows-chevrons/arrow-clockwise-24",
        "mobile-24/arrows-chevrons/arrow-trending-24",
        "mobile-24/arrows-chevrons/back-24",
        "mobile-24/bookmark/bookmark-24",
        "mobile-24/bookmark/bookmark-fill-24",
        "mobile-24/checkmark/checkmark-24",
        "mobile-24/arrows-chevrons/chevron-down-24",
        "mobile-24/arrows-chevrons/chevron-left-24",
        "mobile-24/arrows-chevrons/chevron-right-24",
        "mobile-24/arrows-chevrons/chevron-up-24",
        "mobile-24/alerts-info-help/critical-fill-24",
        "mobile-24/data-clearance/data-clearance-24",
        "mobile-24/delete/delete-24",
        "mobile-24/devices/device-mobile-24",
        "mobile-24/mail/email-shield-24",
        "mobile-24/experiments/experiments-24",
        "mobile-24/extensions/extension-critical-24",
        "mobile-24/extensions/extension-fill-24",
        "mobile-24/extensions/extension-warning-24",
        "mobile-24/external-link/external-link-24",
        "mobile-24/search/find-in-page-24",
        "mobile-24/arrows-chevrons/forward-24",
        "mobile-24/globe/globe-24",
        "mobile-24/history/history-24",
        "mobile-24/home/home-24",
        "mobile-24/alerts-info-help/information-24",
        "mobile-24/alerts-info-help/information-fill-24",
        "mobile-24/lightbulb/lightbulb-24",
        "mobile-24/lock/lock-24",
        "mobile-24/lock/lock-warning-24",
        "mobile-24/permissions/login-24",
        "mobile-24/shopping/packaging-24",
        "mobile-24/passkey/passkey-24",
        "mobile-24/pin/pin-24",
        "mobile-24/pin/pin-fill-24",
        "mobile-24/shopping/price-24",
        "mobile-24/print/print-24",
        "mobile-24/private-mode/private-mode-circle-fill-24",
        "mobile-24/shopping/quality-24",
        "mobile-24/search/search-24",
        "mobile-24/shield/shield-24",
        "mobile-24/shopping/shipping-24",
        "mobile-24/shopping/shopping-24",
        "mobile-24/edit-copy-paste/signature-properties-24",
        "mobile-24/sort/sort-24",
        "mobile-24/subtract/subtract-24",
        "mobile-24/sync/sync-24",
        "mobile-24/tabs/tab-24",
        "mobile-24/themes/themes-24",
        "mobile-24/translate/translate-24",
        "mobile-24/alerts-info-help/warning-24",
        "mobile-24/alerts-info-help/warning-fill-24",
    }
)


def icon_value_fn(rel_path: str) -> str:
    """Convert a ThumbnailChoiceBlock directory-relative path to a stored value.

    Called by ThumbnailChoiceBlock with the file's path relative to thumbnail_directory,
    without extension (e.g. "desktop-16/arrows-and-chevrons/forward-16").

    Returns the CSS logical name, stripping both directory prefix and size suffix:

        "desktop-16/arrows-and-chevrons/forward-16" -> "forward"
        "desktop-16/permissions/auto-play-false"    -> "auto-play-false"
        "desktop-16/screenshot/camera-16"           -> "camera"

    Exception: icons in _COLLIDING_PATHS return their relative path unchanged
    to preserve uniqueness when two files would otherwise produce the same CSS name.
    """
    if rel_path in _COLLIDING_PATHS:
        return rel_path
    return icon_css_name(rel_path.split("/")[-1])


# Maps every legacy ICON_CHOICES stem to its new desktop-16 directory path.
# Values are relative to img/firefox/flare/2026/icons (i.e. "desktop-16/{category}/{stem}").
# Four icons not present in the new set map to "" (empty — renders no icon):
#   android, apple, calendar, toggle-on
ICON_VALUE_MAP: dict[str, str] = {
    "activity": "desktop-16/activity/activity-16",
    "add": "desktop-16/add/add-16",
    "add-circle-fill": "desktop-16/add/add-circle-fill-16",
    "add-text": "desktop-16/text/add-text-16",
    "add-user": "desktop-16/user/add-user-16",
    "all-tabs": "desktop-16/tabs/all-tabs-16",
    "android": "",
    "apple": "",
    "app-menu": "desktop-16/app-menu/app-menu-16",
    "app-menu-space": "desktop-16/app-menu/app-menu-space-16",
    "applied-policy": "desktop-16/policy/applied-policy-16",
    "arrow-clockwise": "desktop-16/arrows-and-chevrons/arrow-clockwise-16",
    "arrow-counterclockwise": "desktop-16/arrows-and-chevrons/arrow-counterclockwise-16",
    "arrow-down-line": "desktop-16/arrows-and-chevrons/arrow-down-line-16",
    "arrow-trending": "desktop-16/arrows-and-chevrons/arrow-trending-16",
    "audio": "desktop-16/media/audio-16",
    "audio-muted": "desktop-16/media/audio-muted-16",
    "authenticated-user": "desktop-16/user/authenticated-user-16",
    "auto-play-false": "desktop-16/permissions/auto-play-false",
    "auto-play-true": "desktop-16/permissions/auto-play-true",
    "avatar-signed-in-fill": "desktop-16/avatars/avatar-signed-in-fill-16",
    "avatar-signed-in-fill-custom-initial": "desktop-16/avatars/avatar-signed-in-fill-custom-initial-16",
    "avatar-signed-in-fill-profile-picture": "desktop-16/avatars/avatar-signed-in-fill-profile-picture-16",
    "avatar-signed-out": "desktop-16/avatars/avatar-signed-out-16",
    "back": "desktop-16/arrows-and-chevrons/back-16",
    "barbell": "desktop-16/profile/barbell-16",
    "bike": "desktop-16/profile/bike-16",
    "block": "desktop-16/block/block-16",
    "block-download": "desktop-16/block/block-download-16",
    "blocked-popup": "desktop-16/permissions/blocked-popup-16",
    "book": "desktop-16/profile/book-16",
    "bookmark": "desktop-16/bookmarks/bookmark-16",
    "bookmark-fill": "desktop-16/bookmarks/bookmark-fill-16",
    "bookmarks-tray": "desktop-16/bookmarks/bookmarks-tray-16",
    "briefcase": "desktop-16/profile/briefcase-16",
    "calendar": "",
    "camera-false": "desktop-16/permissions/camera-false",
    "camera-true": "desktop-16/permissions/camera-true",
    "canvas-false": "desktop-16/permissions/canvas-false",
    "canvas-true": "desktop-16/permissions/canvas-true",
    "checkmark": "desktop-16/checkmarks/checkmark-16",
    "checkmark-circle-fill": "desktop-16/checkmarks/checkmark-circle-fill-16",
    "chevron-double-right": "desktop-16/arrows-and-chevrons/chevron-double-right-16",
    "chevron-down": "desktop-16/arrows-and-chevrons/chevron-down-16",
    "chevron-down-small": "desktop-16/arrows-and-chevrons/chevron-down-small-16",
    "chevron-left": "desktop-16/arrows-and-chevrons/chevron-left-16",
    "chevron-right": "desktop-16/arrows-and-chevrons/chevron-right-16",
    "chevron-up": "desktop-16/arrows-and-chevrons/chevron-up-16",
    "close": "desktop-16/close-cancel-dismiss/close-16",
    "close-circle-fill": "desktop-16/close-cancel-dismiss/close-circle-fill-16",
    "closed-caption": "desktop-16/closed-caption/closed-caption-16",
    "closed-tabs": "desktop-16/tabs/closed-tabs-16",
    "color-picker": "desktop-16/color-picker/color-picker-16",
    "comment": "desktop-16/comment/comment-16",
    "competitiveness": "desktop-16/shopping/competitiveness-16",
    "craft": "desktop-16/profile/craft-16",
    "critical": "desktop-16/alerts-notifications-help/critical-16",
    "critical-fill": "desktop-16/alerts-notifications-help/critical-fill-16",
    "cryptominer-false": "desktop-16/trackers/cryptominer-false",
    "cryptominer-true": "desktop-16/trackers/cryptominer-true",
    "current-view": "desktop-16/page-or-document/current-view-16",
    "cursor-arrow": "desktop-16/arrows-and-chevrons/cursor-arrow-16",
    "dashboard": "desktop-16/dashboard/dashboard-16",
    "data-clearance": "desktop-16/data-clearance/data-clearance-16",
    "delete": "desktop-16/delete/delete-16",
    "device-mobile": "desktop-16/devices/device-mobile-16",
    "diamond": "desktop-16/profile/diamond-16",
    "downloaded-file": "desktop-16/downloads/downloaded-file-16",
    "downloads": "desktop-16/downloads/downloads-16",
    "edit": "desktop-16/pen-pencil/edit-16",
    "edit-active": "desktop-16/pen-pencil/edit-active-16",
    "edit-squiggle": "desktop-16/pen-pencil/edit-squiggle-16",
    "email-mask": "desktop-16/mail/email-mask-16",
    "email-shield": "desktop-16/mail/email-shield-16",
    "error": "desktop-16/alerts-notifications-help/error-16",
    "error-fill": "desktop-16/alerts-notifications-help/error-fill-16",
    "even-spreads": "desktop-16/page-or-document/even-spreads-16",
    "export-data": "desktop-16/import-and-export/export-data-16",
    "extension": "desktop-16/extensions/extension-16",
    "extension-critical": "desktop-16/extensions/extension-critical-16",
    "extension-fill": "desktop-16/extensions/extension-fill-16",
    "extension-warning": "desktop-16/extensions/extension-warning-16",
    "external-link": "desktop-16/external-link/external-link-16",
    "find-in-page": "desktop-16/search/find-in-page-16",
    "fingerprinter-false": "desktop-16/trackers/fingerprinter-false",
    "fingerprinter-true": "desktop-16/trackers/fingerprinter-true",
    "firefox-bridge": "desktop-16/firefox-bridge/firefox-bridge-16",
    "firefox-browser-bridge": "desktop-16/firefox-bridge/firefox-browser-bridge-16",
    "flower": "desktop-16/profile/flower-16",
    "folder": "desktop-16/folder/folder-16",
    "folder-arrow-down": "desktop-16/folder/folder-arrow-down-16",
    "folder-fill": "desktop-16/folder/folder-fill-16",
    "footprints-false": "desktop-16/trackers/footprints-false",
    "footprints-true": "desktop-16/trackers/footprints-true",
    "forward": "desktop-16/arrows-and-chevrons/forward-16",
    "forward-small": "desktop-16/arrows-and-chevrons/forward-small-16",
    "fullscreen-disabled": "desktop-16/fullscreen/fullscreen-disabled-16",
    "fullscreen-exit": "desktop-16/fullscreen/fullscreen-exit-16",
    "fullscreen-expand": "desktop-16/fullscreen/fullscreen-expand-16",
    "fx-view": "desktop-16/view/fx-view-16",
    "gift": "desktop-16/gift/gift-16",
    "globe": "desktop-16/globe/globe-16",
    "globe-slash": "desktop-16/globe/globe-slash-16",
    "hammer": "desktop-16/profile/hammer-16",
    "hand": "desktop-16/hand/hand-16",
    "heart": "desktop-16/profile/heart-16",
    "heart-rate": "desktop-16/profile/heart-rate-16",
    "help": "desktop-16/alerts-notifications-help/help-16",
    "help-fill": "desktop-16/alerts-notifications-help/help-fill-16",
    "highlighter": "desktop-16/highlighter/highlighter-16",
    "history": "desktop-16/history/history-16",
    "home": "desktop-16/home/home-16",
    "horizontal-scrolling": "desktop-16/page-or-document/horizontal-scrolling-16",
    "identity": "desktop-16/user/identity-16",
    "image-tracker-false": "desktop-16/trackers/image-tracker-false",
    "image-tracker-true": "desktop-16/trackers/image-tracker-true",
    "import-data": "desktop-16/import-and-export/import-data-16",
    "import-export": "desktop-16/import-and-export/import-export-16",
    "information": "desktop-16/alerts-notifications-help/information-16",
    "information-fill": "desktop-16/alerts-notifications-help/information-fill-16",
    "layer": "desktop-16/layer/layer-16",
    "leaf": "desktop-16/profile/leaf-16",
    "library": "desktop-16/library/library-16",
    "lightbulb": "desktop-16/lightbulb/lightbulb-16",
    "line-arrow-up": "desktop-16/arrows-and-chevrons/line-arrow-up-16",
    "list": "desktop-16/sort/list-16",
    "list-arrow-left": "desktop-16/sort/list-arrow-left-16",
    "local-host-false": "desktop-16/permissions/local-host-false",
    "local-host-true": "desktop-16/permissions/local-host-true",
    "local-network-false": "desktop-16/permissions/local-network-false",
    "local-network-true2": "desktop-16/permissions/local-network-true2",
    "location-false": "desktop-16/permissions/location-false",
    "location-true": "desktop-16/permissions/location-true",
    "lock": "desktop-16/lock/lock-16",
    "lock-document": "desktop-16/lock/lock-document-16",
    "lock-insecure": "desktop-16/lock/lock-insecure-16",
    "lock-warning": "desktop-16/lock/lock-warning-16",
    "login": "desktop-16/permissions/login-16",
    "makeup": "desktop-16/profile/makeup-16",
    "microphone-false": "desktop-16/permissions/microphone-false",
    "microphone-true": "desktop-16/permissions/microphone-true",
    "midi": "desktop-16/permissions/midi-16",
    "musical-note": "desktop-16/profile/musical-note-16",
    "newsfeed": "desktop-16/news/newsfeed-16",
    "no-spreads": "desktop-16/page-or-document/no-spreads-16",
    "notifications-false": "desktop-16/permissions/notifications-false",
    "notifications-true": "desktop-16/permissions/notifications-true",
    "odd-spreads": "desktop-16/page-or-document/odd-spreads-16",
    "off": "desktop-16/off/off-16",
    "open-tabs": "desktop-16/tabs/open-tabs-16",
    "organizational-unit": "desktop-16/organizational-unit/organizational-unit-16",
    "packaging": "desktop-16/shopping/packaging-16",
    "page-actions": "desktop-16/page-actions/page-actions-16",
    "page-landscape": "desktop-16/page-or-document/page-landscape-16",
    "page-portrait": "desktop-16/page-or-document/page-portrait-16",
    "page-scrolling": "desktop-16/page-or-document/page-scrolling-16",
    "page-thumbnails": "desktop-16/page-or-document/page-thumbnails-16",
    "palette": "desktop-16/profile/palette-16",
    "paperclip": "desktop-16/paperclip/paperclip-16",
    "passkey": "desktop-16/passkey/passkey-16",
    "pause-fill": "desktop-16/media/pause-fill-16",
    "paw-print": "desktop-16/profile/paw-print-16",
    "payment-methods": "desktop-16/payment-methods/payment-methods-16",
    "picture-in-picture-closed": "desktop-16/picture-in-picture-pip/picture-in-picture-closed-16",
    "picture-in-picture-open": "desktop-16/picture-in-picture-pip/picture-in-picture-open-16",
    "pin": "desktop-16/pin/pin-16",
    "pin-fill": "desktop-16/pin/pin-fill-16",
    "plane": "desktop-16/profile/plane-16",
    "play-fill": "desktop-16/media/play-fill-16",
    "playback-forward": "desktop-16/media/playback-forward-16",
    "playback-rewind": "desktop-16/media/playback-rewind-16",
    "plugin-false": "desktop-16/permissions/plugin-false",
    "plugin-true": "desktop-16/permissions/plugin-true",
    "pocket": "desktop-16/pocket/pocket-16",
    "pocket-fill": "desktop-16/pocket/pocket-fill-16",
    "policy": "desktop-16/policy/policy-16",
    "popup-subitem": "desktop-16/permissions/popup-subitem-16",
    "presentation-mode": "desktop-16/page-or-document/presentation-mode-16",
    "price": "desktop-16/shopping/price-16",
    "print": "desktop-16/media/print-16",
    "private-mode-circle-fill": "desktop-16/private-mode/private-mode-circle-fill-16",
    "private-mode-fill": "desktop-16/private-mode/private-mode-fill-16",
    "quality": "desktop-16/shopping/quality-16",
    "reader-mode": "desktop-16/reader-mode/reader-mode-16",
    "remove-user": "desktop-16/user/remove-user-16",
    "screenshot-camera": "desktop-16/screenshot/camera-16",
    "screesnshare-false": "desktop-16/permissions/screesnshare-false",
    "screesnshare-true": "desktop-16/permissions/screesnshare-true",
    "search": "desktop-16/search/search-16",
    "search-in-circle": "desktop-16/search/search-in-circle-16",
    "search-in-circle-right": "desktop-16/search/search-in-circle-right-16",
    "settings": "desktop-16/settings/settings-16",
    "share-macos": "desktop-16/share/share-macos-16",
    "share-winos": "desktop-16/share/share-winos-16",
    "shield": "desktop-16/shield/shield-16",
    "shipping": "desktop-16/shopping/shipping-16",
    "shopping": "desktop-16/shopping/shopping-16",
    "shopping-cart": "desktop-16/profile/shopping-cart-16",
    "show-password-false": "desktop-16/permissions/show-password-false",
    "show-password-true": "desktop-16/permissions/show-password-true",
    "sidebar-collapsed": "desktop-16/sidebar/sidebar-collapsed-16",
    "sidebar-collapsed-right": "desktop-16/sidebar/sidebar-collapsed-right-16",
    "sidebar-expanded": "desktop-16/sidebar/sidebar-expanded-16",
    "sidebar-expanded-right": "desktop-16/sidebar/sidebar-expanded-right-16",
    "sidebar-hidden": "desktop-16/sidebar/sidebar-hidden-16",
    "sidebar-left": "desktop-16/sidebar/sidebar-left-16",
    "sidebar-right": "desktop-16/sidebar/sidebar-right-16",
    "signature-properties": "desktop-16/pen-pencil/signature-properties-16",
    "single-user": "desktop-16/user/single-user-16",
    "soccer-ball": "desktop-16/profile/soccer-ball-16",
    "social-tracker-false": "desktop-16/trackers/social-tracker-false",
    "social-tracker-true": "desktop-16/trackers/social-tracker-true",
    "sort": "desktop-16/sort/sort-16",
    "sparkle-single": "desktop-16/profile/sparkle-single-16",
    "sparkles": "desktop-16/sparkles/sparkles-16",
    "split-view": "desktop-16/split-view/split-view-16",
    "split-view-left": "desktop-16/split-view/split-view-left-16",
    "split-view-right": "desktop-16/split-view/split-view-right-16",
    "storage-false": "desktop-16/permissions/storage-false",
    "storage-true": "desktop-16/permissions/storage-true",
    "subtract": "desktop-16/subtract/subtract-16",
    "subtract-circle-fill": "desktop-16/subtract/subtract-circle-fill-16",
    "sync": "desktop-16/sync/sync-16",
    "synced-tabs": "desktop-16/sync/synced-tabs-16",
    "tab": "desktop-16/tabs/tab-16",
    "tab-group": "desktop-16/tabs/tab-group-16",
    "tab-notes": "desktop-16/tabs/tab-notes-16",
    "taskbar-add-tab": "desktop-16/tabs/taskbar-add-tab-16",
    "taskbar-move-tab": "desktop-16/tabs/taskbar-move-tab-16",
    "taskbar-remove-tab": "desktop-16/tabs/taskbar-remove-tab-16",
    "text-cursor": "desktop-16/text/text-cursor-16",
    "themes": "desktop-16/themes/themes-16",
    "toggle-on": "",
    "top-sites": "desktop-16/top-sites/top-sites-16",
    "tracking-cookies-false": "desktop-16/trackers/tracking-cookies-false",
    "tracking-cookies-true": "desktop-16/trackers/tracking-cookies-true",
    "translate": "desktop-16/translate/translate-20",
    "trending": "desktop-16/trending/trending-16",
    "unauthenticated-user": "desktop-16/user/unauthenticated-user-16",
    "update": "desktop-16/arrows-and-chevrons/update-16",
    "update-circle-fill": "desktop-16/alerts-notifications-help/update-circle-fill-16",
    "users": "desktop-16/user/users-16",
    "vertical-scrolling": "desktop-16/page-or-document/vertical-scrolling-16",
    "vertical-tabs": "desktop-16/tabs/vertical-tabs-16",
    "video-game-controller": "desktop-16/profile/video-game-controller-16",
    "vpn-disconnected": "desktop-16/vpn/vpn-disconnected-16",
    "vpn-off": "desktop-16/vpn/vpn-off-16",
    "vpn-on": "desktop-16/vpn/vpn-on-16",
    "vpn-on-off-site": "desktop-16/vpn/vpn-on-off-site-16",
    "warning": "desktop-16/alerts-notifications-help/warning-16",
    "warning-fill": "desktop-16/alerts-notifications-help/warning-fill-16",
    "window": "desktop-16/window/window-16",
    "window-firefox": "desktop-16/window/window-firefox-16",
    "wrapped-scrolling": "desktop-16/page-or-document/wrapped-scrolling-16",
    "xr-false": "desktop-16/permissions/xr-false",
    "xr-true": "desktop-16/permissions/xr-true",
}
