# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""English labels and their translations for the main navigation snippet.

Copied from the ``navigation-firefox.ftl`` files in www-firefox-l10n,
with brand terms expanded.
"""

NAVIGATION_LABELS = {
    "navigation-browser": "Browser",
    "navigation-mobile": "Mobile",
    "navigation-enterprise": "Enterprise",
    "navigation-whats-new": "What’s New",
    "navigation-whats-next": "What’s Next",
    "navigation-extensions-and-themes": "Extensions & Themes",
    "navigation-support": "Support",
    "navigation-download-firefox": "Download Firefox",
    "navigation-features": "Features",
    "navigation-protection": "Protection",
    "navigation-control": "Control",
    "navigation-focus": "Focus",
    "navigation-about-firefox-features": "About Firefox features",
    "navigation-features-all": "View all Firefox Features",
    "navigation-resources": "Resources",
    "navigation-data-protection": "Data Protection",
    "navigation-blog": "Blog",
    "navigation-podcast": "Podcast",
    "navigation-newsletter": "Newsletter",
    "navigation-release-notes": "Release Notes",
}

NAVIGATION_TRANSLATIONS = {
    "en-GB": {
        "navigation-browser": "Browser",
        "navigation-mobile": "Mobile",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "What’s New",
        "navigation-whats-next": "What’s Next",
        "navigation-extensions-and-themes": "Extensions & Themes",
        "navigation-support": "Support",
        "navigation-download-firefox": "Download Firefox",
        "navigation-features": "Features",
        "navigation-protection": "Protection",
        "navigation-control": "Control",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "About Firefox features",
        "navigation-features-all": "View all Firefox Features",
        "navigation-resources": "Resources",
        "navigation-data-protection": "Data Protection",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Release Notes",
    },
    "en-CA": {
        "navigation-browser": "Browser",
        "navigation-mobile": "Mobile",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "What’s New",
        "navigation-whats-next": "What’s Next",
        "navigation-extensions-and-themes": "Extensions & Themes",
        "navigation-support": "Support",
        "navigation-download-firefox": "Download Firefox",
        "navigation-features": "Features",
        "navigation-protection": "Protection",
        "navigation-control": "Control",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "About Firefox features",
        "navigation-features-all": "View all Firefox Features",
        "navigation-resources": "Resources",
        "navigation-data-protection": "Data Protection",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Release Notes",
    },
    "de": {
        "navigation-browser": "Browser",
        "navigation-mobile": "Mobile",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "Was ist neu",
        "navigation-whats-next": "Was passiert jetzt?",
        "navigation-extensions-and-themes": "Erweiterungen und Themen",
        "navigation-support": "Hilfe",
        "navigation-download-firefox": "Firefox herunterladen",
        "navigation-features": "Funktionen",
        "navigation-protection": "Schutz",
        "navigation-control": "Kontrolle",
        "navigation-focus": "Klar",
        "navigation-about-firefox-features": "Über Firefox-Funktionen",
        "navigation-features-all": "Alle Firefox-Funktionen ansehen",
        "navigation-resources": "Ressourcen",
        "navigation-data-protection": "Datenschutz",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Versionshinweise",
    },
    "fr": {
        "navigation-browser": "Navigateur",
        "navigation-mobile": "Mobile",
        "navigation-enterprise": "Entreprise",
        "navigation-whats-new": "Nouveautés",
        "navigation-whats-next": "Et ensuite\xa0?",
        "navigation-extensions-and-themes": "Extensions et thèmes",
        "navigation-support": "Assistance",
        "navigation-download-firefox": "Télécharger Firefox",
        "navigation-features": "Fonctionnalités",
        "navigation-protection": "Protection",
        "navigation-control": "Contrôle",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "À propos des fonctionnalités de Firefox",
        "navigation-features-all": "Voir toutes les fonctionnalités de Firefox",
        "navigation-resources": "Ressources",
        "navigation-data-protection": "Protection des données",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Notes de mise à jour",
    },
    "es-AR": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Teléfono celular",
        "navigation-enterprise": "Empresa",
        "navigation-whats-new": "Qué hay de nuevo",
        "navigation-whats-next": "Qué sigue",
        "navigation-extensions-and-themes": "Extensiones y temas",
        "navigation-support": "Ayuda",
        "navigation-download-firefox": "Descargá Firefox",
        "navigation-features": "Características",
        "navigation-protection": "Protección",
        "navigation-control": "Control",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Acerca de las funciones de Firefox",
        "navigation-features-all": "Ver todas las funciones de Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Protección de datos",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Boletín informativo",
        "navigation-release-notes": "Notas de la versión",
    },
    "es-CL": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Móvil",
        "navigation-enterprise": "Empresa",
        "navigation-whats-new": "Qué hay de nuevo",
        "navigation-whats-next": "Qué sigue",
        "navigation-extensions-and-themes": "Extensiones y temas",
        "navigation-support": "Soporte",
        "navigation-download-firefox": "Bajar Firefox",
        "navigation-features": "Características",
        "navigation-protection": "Protección",
        "navigation-control": "Control",
        "navigation-focus": "Foco",
        "navigation-about-firefox-features": "Acerca de las funcionalidades de Firefox",
        "navigation-features-all": "Ver todas las funcionalidades de Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Protección de Datos",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Boletín",
        "navigation-release-notes": "Notas de la versión",
    },
    "es-ES": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Móvil",
        "navigation-enterprise": "Empresa",
        "navigation-whats-new": "Qué hay de nuevo",
        "navigation-whats-next": "Qué sigue",
        "navigation-extensions-and-themes": "Extensiones y temas",
        "navigation-support": "Ayuda",
        "navigation-download-firefox": "Descargar Firefox",
        "navigation-features": "Características",
        "navigation-protection": "Protección",
        "navigation-control": "Control",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Acerca de las funciones de Firefox",
        "navigation-features-all": "Ver todas las funciones de Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Protección de datos",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Boletín",
        "navigation-release-notes": "Notas de la versión",
    },
    "es-MX": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Móvil",
        "navigation-enterprise": "Empresa",
        "navigation-whats-new": "Qué hay de nuevo",
        "navigation-whats-next": "¿Qué sigue?",
        "navigation-extensions-and-themes": "Extensiones y temas",
        "navigation-support": "Soporte",
        "navigation-download-firefox": "Descargar Firefox",
        "navigation-features": "Características",
        "navigation-protection": "Protección",
        "navigation-control": "Control",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Acerca de las características de Firefox",
        "navigation-features-all": "Ver todas las características de Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Protección de datos",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Boletín",
        "navigation-release-notes": "Notas de la versión",
    },
    "it": {
        "navigation-browser": "Browser",
        "navigation-mobile": "Mobile",
        "navigation-enterprise": "Aziende",
        "navigation-whats-new": "Novità",
        "navigation-whats-next": "In arrivo",
        "navigation-extensions-and-themes": "Estensioni e temi",
        "navigation-support": "Supporto",
        "navigation-download-firefox": "Scarica Firefox",
        "navigation-features": "Caratteristiche",
        "navigation-protection": "Protezione",
        "navigation-control": "Controllo",
        "navigation-focus": "Concentrazione",
        "navigation-about-firefox-features": "Informazioni sulle funzioni di Firefox",
        "navigation-features-all": "Visualizza tutte le caratteristiche di Firefox",
        "navigation-resources": "Risorse",
        "navigation-data-protection": "Protezione dei dati",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Note di versione",
    },
    "ja": {
        "navigation-browser": "ブラウザー",
        "navigation-mobile": "モバイル",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "新着情報",
        "navigation-whats-next": "次のステップ",
        "navigation-extensions-and-themes": "拡張機能とテーマ",
        "navigation-support": "サポート",
        "navigation-download-firefox": "Firefox をダウンロード",
        "navigation-features": "機能",
        "navigation-protection": "保護",
        "navigation-control": "管理",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Firefox の機能について",
        "navigation-features-all": "Firefox の全機能を見る",
        "navigation-resources": "リソース",
        "navigation-data-protection": "データ保護",
        "navigation-blog": "ブログ",
        "navigation-podcast": "ポッドキャスト",
        "navigation-newsletter": "ニュースレター",
        "navigation-release-notes": "リリースノート",
    },
    "nl": {
        "navigation-browser": "Browser",
        "navigation-mobile": "Mobiel",
        "navigation-enterprise": "Ondernemingen",
        "navigation-whats-new": "Wat is er nieuw",
        "navigation-whats-next": "Volgende stap",
        "navigation-extensions-and-themes": "Extensies & Thema’s",
        "navigation-support": "Ondersteuning",
        "navigation-download-firefox": "Firefox downloaden",
        "navigation-features": "Functies",
        "navigation-protection": "Bescherming",
        "navigation-control": "Besturing",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Over Firefox-functies",
        "navigation-features-all": "Alle Firefox-functies bekijken",
        "navigation-resources": "Bronnen",
        "navigation-data-protection": "Gegevensbeveiliging",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Nieuwsbrief",
        "navigation-release-notes": "Uitgaveopmerkingen",
    },
    "pl": {
        "navigation-browser": "Przeglądarka",
        "navigation-mobile": "Na\xa0telefony",
        "navigation-enterprise": "Dla firm",
        "navigation-whats-new": "Co nowego",
        "navigation-whats-next": "Plany na przyszłość",
        "navigation-extensions-and-themes": "Rozszerzenia i\xa0motywy",
        "navigation-support": "Pomoc",
        "navigation-download-firefox": "Pobierz Firefox",
        "navigation-features": "Możliwości",
        "navigation-protection": "Ochrona",
        "navigation-control": "Kontrola",
        "navigation-focus": "Skupienie",
        "navigation-about-firefox-features": "O\xa0funkcjach Firefox",
        "navigation-features-all": "Wszystkie funkcje Firefox",
        "navigation-resources": "Zasoby",
        "navigation-data-protection": "Ochrona danych",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Informacje o\xa0wydaniu",
    },
    "pt-BR": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Dispositivo móvel",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "Novidades",
        "navigation-whats-next": "O que vem a seguir",
        "navigation-extensions-and-themes": "Extensões e temas",
        "navigation-support": "Suporte",
        "navigation-download-firefox": "Baixe o Firefox",
        "navigation-features": "Funcionalidades",
        "navigation-protection": "Proteção",
        "navigation-control": "Controle",
        "navigation-focus": "Foco",
        "navigation-about-firefox-features": "Informações sobre recursos do Firefox",
        "navigation-features-all": "Veja todos os recursos do Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Proteção de dados",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Boletim informativo",
        "navigation-release-notes": "Notas de atualização",
    },
    "pt-PT": {
        "navigation-browser": "Navegador",
        "navigation-mobile": "Dispositivos móveis",
        "navigation-enterprise": "Empresa",
        "navigation-whats-new": "Novidades",
        "navigation-whats-next": "Próximos passos",
        "navigation-extensions-and-themes": "Extensões e temas",
        "navigation-support": "Apoio",
        "navigation-download-firefox": "Transferir o Firefox",
        "navigation-features": "Funcionalidades",
        "navigation-protection": "Proteção",
        "navigation-control": "Controlo",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Sobre Firefox funcionalidades",
        "navigation-features-all": "Ver todas as funcionalidades do Firefox",
        "navigation-resources": "Recursos",
        "navigation-data-protection": "Proteção de dados",
        "navigation-blog": "Blogue",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Newsletter",
        "navigation-release-notes": "Notas de lançamento",
    },
    "ru": {
        "navigation-browser": "Браузер",
        "navigation-mobile": "Мобильный",
        "navigation-enterprise": "Для предприятий",
        "navigation-whats-new": "Что нового",
        "navigation-whats-next": "Что дальше",
        "navigation-extensions-and-themes": "Расширения и темы",
        "navigation-support": "Поддержка",
        "navigation-download-firefox": "Скачать Firefox",
        "navigation-features": "Возможности",
        "navigation-protection": "Защита",
        "navigation-control": "Управление",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "О функциях Firefox",
        "navigation-features-all": "Просмотреть все функции Firefox",
        "navigation-resources": "Ресурсы",
        "navigation-data-protection": "Защита данных",
        "navigation-blog": "Блог",
        "navigation-podcast": "Подкаст",
        "navigation-newsletter": "Новостная рассылка",
        "navigation-release-notes": "Примечания к выпуску",
    },
    "zh-CN": {
        "navigation-browser": "浏览器",
        "navigation-mobile": "移动版",
        "navigation-enterprise": "企业版",
        "navigation-whats-new": "新版变化",
        "navigation-whats-next": "下一步",
        "navigation-extensions-and-themes": "扩展和主题",
        "navigation-support": "技术支持",
        "navigation-download-firefox": "下载 Firefox",
        "navigation-features": "特色",
        "navigation-protection": "保护",
        "navigation-control": "控制",
        "navigation-focus": "专注",
        "navigation-about-firefox-features": "关于 Firefox 的功能",
        "navigation-features-all": "尽览 Firefox 特色功能",
        "navigation-resources": "资源",
        "navigation-data-protection": "数据保护",
        "navigation-blog": "博客",
        "navigation-podcast": "播客",
        "navigation-newsletter": "新闻通讯",
        "navigation-release-notes": "发行说明",
    },
    "id": {
        "navigation-browser": "Peramban",
        "navigation-mobile": "Seluler",
        "navigation-enterprise": "Enterprise",
        "navigation-whats-new": "Apa Yang Baru",
        "navigation-whats-next": "Yang Akan Datang",
        "navigation-extensions-and-themes": "Ekstensi & Tema",
        "navigation-support": "Dukungan",
        "navigation-download-firefox": "Unduh Firefox",
        "navigation-features": "Fitur",
        "navigation-protection": "Perlindungan",
        "navigation-control": "Kendali",
        "navigation-focus": "Focus",
        "navigation-about-firefox-features": "Tentang fitur Firefox",
        "navigation-features-all": "Lihat semua Fitur Firefox",
        "navigation-resources": "Sumber Daya",
        "navigation-data-protection": "Perlindungan Data",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Buletin",
        "navigation-release-notes": "Catatan Rilis",
    },
    "tr": {
        "navigation-browser": "Tarayıcı",
        "navigation-mobile": "Mobil",
        "navigation-enterprise": "Kurumsal",
        "navigation-whats-new": "Yeni neler var?",
        "navigation-whats-next": "Sırada ne var?",
        "navigation-extensions-and-themes": "Uzantılar ve temalar",
        "navigation-support": "Destek",
        "navigation-download-firefox": "Firefox’u indir",
        "navigation-features": "Özellikler",
        "navigation-protection": "Koruma",
        "navigation-control": "Kontrol",
        "navigation-focus": "Odaklanma",
        "navigation-about-firefox-features": "Firefox özellikleri hakkında",
        "navigation-features-all": "Tüm Firefox özelliklerini görün",
        "navigation-resources": "Kaynaklar",
        "navigation-data-protection": "Veri Koruması",
        "navigation-blog": "Blog",
        "navigation-podcast": "Podcast",
        "navigation-newsletter": "Bülten",
        "navigation-release-notes": "Sürüm Notları",
    },
}
