# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.16 on 2026-09-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedPagePermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Translated pages",
                "permissions": [
                    ("add_translated_page", "Add"),
                    ("bulk_delete_translated_page", "Bulk delete"),
                    ("change_translated_page", "Edit"),
                    ("lock_translated_page", "Lock"),
                    ("publish_translated_page", "Publish"),
                    ("unlock_translated_page", "Unlock"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
