name: Post-deploy asset check

run-name: Asset check for ${{ inputs.branch }} @ ${{ inputs.git_sha }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch of mozmeao/springfield that was deployed (eg. main|stage|prod)
        required: true
      git_sha:
        description: Git SHA that was deployed
        required: true
      origin_hostname:
        description: Fully qualified base URL for the origin server
        required: true
      cdn_hostname:
        description: Fully qualified base URL for the CDN (eg. https://www.firefox.com)
        required: true

jobs:
  asset-check:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: springfield.settings
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt

      - name: Pull release image
        run: docker pull mozmeao/springfield:${{ inputs.git_sha }}

      - name: Extract manifest from release image
        run: |
          set -euo pipefail
          container_id=$(docker create mozmeao/springfield:${{ inputs.git_sha }})
          trap 'docker rm "$container_id" >/dev/null 2>&1 || true' EXIT
          mkdir -p extracted-static
          docker cp "$container_id":/app/static/staticfiles.json extracted-static/staticfiles.json

      - name: Verify deployed assets are available
        run: |
          python manage.py check_static_assets \
            --origin-host "${{ inputs.origin_hostname }}" \
            --cdn-host "${{ inputs.cdn_hostname }}" \
            --manifest-path "extracted-static/staticfiles.json"
